BEGIN;

  DROP TABLE IF EXISTS bcfishpass.crossings_sidechannel_upstream_startpoints;
  CREATE TABLE bcfishpass.crossings_sidechannel_upstream_startpoints (
    aggregated_crossings_id text,
    blue_line_key integer,
    downstream_route_measure integer,
    primary key (aggregated_crossings_id, blue_line_key)
  );

  DROP MATERIALIZED VIEW IF EXISTS bcfishpass.crossings_wcrp_vw;

  DROP TABLE IF EXISTS bcfishpass.crossings_upstream_habitat_wcrp;

  CREATE TABLE bcfishpass.crossings_upstream_habitat_wcrp (
      aggregated_crossings_id text NOT NULL,
      watershed_group_code character varying(4),
      
      ch_spawning_km double precision DEFAULT 0,
      ch_rearing_km double precision DEFAULT 0,
      ch_spawning_belowupstrbarriers_km double precision DEFAULT 0,
      ch_rearing_belowupstrbarriers_km double precision DEFAULT 0,
      
      co_spawning_km double precision DEFAULT 0,
      co_rearing_km double precision DEFAULT 0,
      co_spawning_belowupstrbarriers_km double precision DEFAULT 0,
      co_rearing_belowupstrbarriers_km double precision DEFAULT 0,
      
      sk_spawning_km double precision DEFAULT 0,
      sk_rearing_km double precision DEFAULT 0,
      sk_spawning_belowupstrbarriers_km double precision DEFAULT 0,
      sk_rearing_belowupstrbarriers_km double precision DEFAULT 0,
      
      st_spawning_km double precision DEFAULT 0,
      st_rearing_km double precision DEFAULT 0,
      st_spawning_belowupstrbarriers_km double precision DEFAULT 0,
      st_rearing_belowupstrbarriers_km double precision DEFAULT 0,

      wct_spawning_km double precision DEFAULT 0,
      wct_rearing_km double precision DEFAULT 0,
      wct_spawning_belowupstrbarriers_km double precision DEFAULT 0,
      wct_rearing_belowupstrbarriers_km double precision DEFAULT 0,

      all_spawning_km double precision DEFAULT 0,
      all_spawning_belowupstrbarriers_km double precision DEFAULT 0,
      all_rearing_km double precision DEFAULT 0,
      all_rearing_belowupstrbarriers_km double precision DEFAULT 0,
      all_spawningrearing_km double precision DEFAULT 0,
      all_spawningrearing_belowupstrbarriers_km double precision DEFAULT 0,

      ch_spawningrearing_km double precision DEFAULT 0,
      ch_spawningrearing_belowupstrbarriers_km double precision DEFAULT 0,
      co_spawningrearing_km double precision DEFAULT 0,
      co_spawningrearing_belowupstrbarriers_km double precision DEFAULT 0,
      sk_spawningrearing_km double precision DEFAULT 0,
      sk_spawningrearing_belowupstrbarriers_km double precision DEFAULT 0,
      st_spawningrearing_km double precision DEFAULT 0,
      st_spawningrearing_belowupstrbarriers_km double precision DEFAULT 0,
      wct_spawningrearing_km double precision DEFAULT 0,
      wct_spawningrearing_belowupstrbarriers_km double precision DEFAULT 0,
      PRIMARY KEY (aggregated_crossings_id)
  );

  -- re-create crossings_wcrp, but as a table not a materialized view 
  -- this allows custom updates to the underlying data.
  DROP TABLE IF EXISTS bcfishpass.crossings_wcrp;
  CREATE TABLE bcfishpass.crossings_wcrp (
    aggregated_crossings_id                         text                   ,
    modelled_crossing_id                            integer                ,
    crossing_source                                 text                   ,
    crossing_feature_type                           text                   ,
    pscis_status                                    text                   ,
    crossing_type_code                              text                   ,
    crossing_subtype_code                           text                   ,
    barrier_status                                  text                   ,
    pscis_road_name                                 text                   ,
    pscis_stream_name                               text                   ,
    pscis_assessment_comment                        text                   ,
    pscis_assessment_date                           date                   ,
    transport_line_structured_name_1                text                   ,
    rail_track_name                                 text                   ,
    dam_name                                        text                   ,
    dam_height                                      double precision       ,
    dam_owner                                       text                   ,
    dam_use                                         text                   ,
    dam_operating_status                            text                   ,
    utm_zone                                        integer                ,
    utm_easting                                     integer                ,
    utm_northing                                    integer                ,
    blue_line_key                                   integer                ,
    downstream_route_measure                        double precision       ,
    wscode                                          ltree                  ,
    localcode                                       ltree                  ,
    watershed_group_code                            text                   ,
    gnis_stream_name                                text                   ,
    barriers_anthropogenic_dnstr                    text                   ,
    barriers_anthropogenic_dnstr_count              integer                ,
    barriers_anthropogenic_habitat_wcrp_upstr       text                   ,
    barriers_anthropogenic_habitat_wcrp_upstr_count integer                ,
    barriers_ch_cm_co_pk_sk_dnstr                   text                   ,
    barriers_st_dnstr                               text                   ,
    barriers_wct_dnstr                              text                   ,
    ch_spawning_km                                  double precision       ,
    ch_rearing_km                                   double precision       ,
    ch_spawningrearing_km                           double precision       ,
    ch_spawning_belowupstrbarriers_km               double precision       ,
    ch_rearing_belowupstrbarriers_km                double precision       ,
    ch_spawningrearing_belowupstrbarriers_km        double precision       ,
    cm_spawning_km                                  double precision       ,
    cm_spawning_belowupstrbarriers_km               double precision       ,
    co_spawning_km                                  double precision       ,
    co_rearing_km                                   double precision       ,
    co_spawningrearing_km                           double precision       ,
    co_rearing_ha                                   double precision       ,
    co_spawning_belowupstrbarriers_km               double precision       ,
    co_rearing_belowupstrbarriers_km                double precision       ,
    co_spawningrearing_belowupstrbarriers_km        double precision       ,
    co_rearing_belowupstrbarriers_ha                double precision       ,
    pk_spawning_km                                  double precision       ,
    pk_spawning_belowupstrbarriers_km               double precision       ,
    sk_spawning_km                                  double precision       ,
    sk_rearing_km                                   double precision       ,
    sk_spawningrearing_km                           double precision       ,
    sk_rearing_ha                                   double precision       ,
    sk_spawning_belowupstrbarriers_km               double precision       ,
    sk_rearing_belowupstrbarriers_km                double precision       ,
    sk_spawningrearing_belowupstrbarriers_km        double precision       ,
    sk_rearing_belowupstrbarriers_ha                double precision       ,
    st_spawning_km                                  double precision       ,
    st_rearing_km                                   double precision       ,
    st_spawningrearing_km                           double precision       ,
    st_spawning_belowupstrbarriers_km               double precision       ,
    st_rearing_belowupstrbarriers_km                double precision       ,
    st_spawningrearing_belowupstrbarriers_km        double precision       ,
    wct_spawning_km                                 double precision       ,
    wct_rearing_km                                  double precision       ,
    wct_spawningrearing_km                          double precision       ,
    wct_spawning_belowupstrbarriers_km              double precision       ,
    wct_rearing_belowupstrbarriers_km               double precision       ,
    wct_spawningrearing_belowupstrbarriers_km       double precision       ,
    all_spawning_km                                 double precision       ,
    all_spawning_belowupstrbarriers_km              double precision       ,
    all_rearing_km                                  double precision       ,
    all_rearing_belowupstrbarriers_km               double precision       ,
    all_spawningrearing_km                          double precision       ,
    all_spawningrearing_belowupstrbarriers_km       double precision       ,
    geom                                            geometry(PointZM,3005) ,
    PRIMARY KEY (aggregated_crossings_id)
  );

  -- for backwards compatability, add a view on top of it
  DROP VIEW IF EXISTS bcfishpass.crossings_wcrp_vw;
  CREATE VIEW bcfishpass.crossings_wcrp_vw AS
  SELECT
    a.aggregated_crossings_id,
    a.modelled_crossing_id,
    a.crossing_source,
    a.crossing_feature_type,
    a.pscis_status,
    a.crossing_type_code,
    a.crossing_subtype_code,
    a.barrier_status,
    a.pscis_road_name,
    a.pscis_stream_name,
    a.pscis_assessment_comment,
    a.pscis_assessment_date,
    a.transport_line_structured_name_1,
    a.rail_track_name,
    a.dam_name,
    a.dam_height,
    a.dam_owner,
    a.dam_use,
    a.dam_operating_status,
    a.utm_zone,
    a.utm_easting,
    a.utm_northing,
    a.blue_line_key,
    a.downstream_route_measure,
    a.wscode,
    a.localcode,
    a.watershed_group_code,
    a.gnis_stream_name,
    a.barriers_anthropogenic_dnstr,
    a.barriers_anthropogenic_dnstr_count,
    a.barriers_anthropogenic_habitat_wcrp_upstr,
    a.barriers_anthropogenic_habitat_wcrp_upstr_count,
    a.barriers_ch_cm_co_pk_sk_dnstr,
    a.barriers_st_dnstr,
    a.barriers_wct_dnstr,
    a.ch_spawning_km,
    a.ch_rearing_km,
    a.ch_spawningrearing_km,
    a.ch_spawning_belowupstrbarriers_km,
    a.ch_rearing_belowupstrbarriers_km,
    a.ch_spawningrearing_belowupstrbarriers_km,
    a.cm_spawning_km,
    a.cm_spawning_belowupstrbarriers_km,
    a.co_spawning_km,
    a.co_rearing_km,
    a.co_spawningrearing_km,
    a.co_rearing_ha,
    a.co_spawning_belowupstrbarriers_km,
    a.co_rearing_belowupstrbarriers_km,
    a.co_spawningrearing_belowupstrbarriers_km,
    a.co_rearing_belowupstrbarriers_ha,
    a.pk_spawning_km,
    a.pk_spawning_belowupstrbarriers_km,
    a.sk_spawning_km,
    a.sk_rearing_km,
    a.sk_spawningrearing_km,
    a.sk_rearing_ha,
    a.sk_spawning_belowupstrbarriers_km,
    a.sk_rearing_belowupstrbarriers_km,
    a.sk_spawningrearing_belowupstrbarriers_km,
    a.sk_rearing_belowupstrbarriers_ha,
    a.st_spawning_km,
    a.st_rearing_km,
    a.st_spawningrearing_km,
    a.st_spawning_belowupstrbarriers_km,
    a.st_rearing_belowupstrbarriers_km,
    a.st_spawningrearing_belowupstrbarriers_km,
    a.wct_spawning_km,
    a.wct_rearing_km,
    a.wct_spawningrearing_km,
    a.wct_spawning_belowupstrbarriers_km,
    a.wct_rearing_belowupstrbarriers_km,
    a.wct_spawningrearing_belowupstrbarriers_km,
    a.all_spawning_km,
    a.all_spawning_belowupstrbarriers_km,
    a.all_rearing_km,
    a.all_rearing_belowupstrbarriers_km,
    a.all_spawningrearing_km,
    a.all_spawningrearing_belowupstrbarriers_km,
    r.set_id,
    r.total_hab_gain_set,
    r.num_barriers_set,
    r.avg_gain_per_barrier,
    r.dnstr_set_ids,
    r.rank_avg_gain_per_barrier,
    r.rank_avg_gain_tiered,
    r.rank_total_upstr_hab,
    r.rank_combined,
    r.tier_combined,
    a.geom
  FROM bcfishpass.crossings_wcrp a
  LEFT JOIN bcfishpass.wcrp_ranked_barriers r ON a.aggregated_crossings_id = r.aggregated_crossings_id;


COMMIT;
