-- add standard access codes to crossings_vw

BEGIN;
 
  ALTER TABLE bcfishpass.crossings_upstream_access
  ADD COLUMN access_bt       integer,
  ADD COLUMN access_ch       integer,
  ADD COLUMN access_cm       integer,
  ADD COLUMN access_co       integer,
  ADD COLUMN access_pk       integer,
  ADD COLUMN access_sk       integer,
  ADD COLUMN access_salmon   integer,
  ADD COLUMN access_ct_dv_rb integer,
  ADD COLUMN access_st       integer,
  ADD COLUMN access_wct      integer;
 

  DROP MATERIALIZED VIEW bcfishpass.crossings_vw;

  CREATE MATERIALIZED VIEW bcfishpass.crossings_vw AS
  SELECT DISTINCT ON (c.aggregated_crossings_id) c.aggregated_crossings_id,
    c.stream_crossing_id,
    c.dam_id,
    c.user_crossing_misc_id,
    c.modelled_crossing_id,
    c.crossing_source,
    c.crossing_feature_type,
    c.pscis_status,
    c.crossing_type_code,
    c.crossing_subtype_code,
    array_to_string(c.modelled_crossing_type_source, ';'::text) AS modelled_crossing_type_source,
    c.barrier_status,
    c.pscis_road_name,
    c.pscis_stream_name,
    c.pscis_assessment_comment,
    c.pscis_assessment_date,
    c.pscis_final_score,
    c.transport_line_structured_name_1,
    c.transport_line_type_description,
    c.transport_line_surface_description,
    c.ften_forest_file_id,
    c.ften_road_section_id,
    c.ften_file_type_description,
    c.ften_client_number,
    c.ften_client_name,
    c.ften_life_cycle_status_code,
    c.ften_map_label,
    c.rail_track_name,
    c.rail_owner_name,
    c.rail_operator_english_name,
    c.ogc_proponent,
    c.dam_name,
    c.dam_height,
    c.dam_owner,
    c.dam_use,
    c.dam_operating_status,
    c.utm_zone,
    c.utm_easting,
    c.utm_northing,
    t.map_tile_display_name AS dbm_mof_50k_grid,
    c.linear_feature_id,
    c.blue_line_key,
    c.watershed_key,
    c.downstream_route_measure,
    c.wscode_ltree AS wscode,
    c.localcode_ltree AS localcode,
    c.watershed_group_code,
    c.gnis_stream_name,
    c.stream_order,
    c.stream_magnitude,
    s.upstream_area_ha,
    s.stream_order_parent,
    s.stream_order_max,
    s.map_upstream,
    s.channel_width,
    s.mad_m3s,
    a.access_bt,
    a.access_ch,
    a.access_cm,
    a.access_co,
    a.access_pk,
    a.access_sk,
    a.access_salmon,
    a.access_ct_dv_rb,
    a.access_st,
    a.access_wct,
    array_to_string(cdo.observedspp_dnstr, ';'::text) AS observedspp_dnstr,
    array_to_string(cuo.observedspp_upstr, ';'::text) AS observedspp_upstr,
    array_to_string(cd.features_dnstr, ';'::text) AS crossings_dnstr,
    array_to_string(ad.features_dnstr, ';'::text) AS barriers_anthropogenic_dnstr,
    COALESCE(array_length(ad.features_dnstr, 1), 0) AS barriers_anthropogenic_dnstr_count,
    array_to_string(au.features_upstr, ';'::text) AS barriers_anthropogenic_upstr,
    COALESCE(array_length(au.features_upstr, 1), 0) AS barriers_anthropogenic_upstr_count,
    array_to_string(aum.barriers_upstr_bt, ';'::text) AS barriers_anthropogenic_bt_upstr,
    COALESCE(array_length(aum.barriers_upstr_bt, 1), 0) AS barriers_anthropogenic_upstr_bt_count,
    array_to_string(aum.barriers_upstr_ch_cm_co_pk_sk, ';'::text) AS barriers_anthropogenic_ch_cm_co_pk_sk_upstr,
    COALESCE(array_length(aum.barriers_upstr_ch_cm_co_pk_sk, 1), 0) AS barriers_anthropogenic_ch_cm_co_pk_sk_upstr_count,
    array_to_string(aum.barriers_upstr_st, ';'::text) AS barriers_anthropogenic_st_upstr,
    COALESCE(array_length(aum.barriers_upstr_st, 1), 0) AS barriers_anthropogenic_st_upstr_count,
    array_to_string(aum.barriers_upstr_wct, ';'::text) AS barriers_anthropogenic_wct_upstr,
    COALESCE(array_length(aum.barriers_upstr_wct, 1), 0) AS barriers_anthropogenic_wct_upstr_count,
    a.gradient,
    a.total_network_km,
    a.total_stream_km,
    a.total_lakereservoir_ha,
    a.total_wetland_ha,
    a.total_slopeclass03_waterbodies_km,
    a.total_slopeclass03_km,
    a.total_slopeclass05_km,
    a.total_slopeclass08_km,
    a.total_slopeclass15_km,
    a.total_slopeclass22_km,
    a.total_slopeclass30_km,
    a.total_belowupstrbarriers_network_km,
    a.total_belowupstrbarriers_stream_km,
    a.total_belowupstrbarriers_lakereservoir_ha,
    a.total_belowupstrbarriers_wetland_ha,
    a.total_belowupstrbarriers_slopeclass03_waterbodies_km,
    a.total_belowupstrbarriers_slopeclass03_km,
    a.total_belowupstrbarriers_slopeclass05_km,
    a.total_belowupstrbarriers_slopeclass08_km,
    a.total_belowupstrbarriers_slopeclass15_km,
    a.total_belowupstrbarriers_slopeclass22_km,
    a.total_belowupstrbarriers_slopeclass30_km,
    array_to_string(a.barriers_bt_dnstr, ';'::text) AS barriers_bt_dnstr,
    a.bt_network_km,
    a.bt_stream_km,
    a.bt_lakereservoir_ha,
    a.bt_wetland_ha,
    a.bt_slopeclass03_waterbodies_km,
    a.bt_slopeclass03_km,
    a.bt_slopeclass05_km,
    a.bt_slopeclass08_km,
    a.bt_slopeclass15_km,
    a.bt_slopeclass22_km,
    a.bt_slopeclass30_km,
    a.bt_belowupstrbarriers_network_km,
    a.bt_belowupstrbarriers_stream_km,
    a.bt_belowupstrbarriers_lakereservoir_ha,
    a.bt_belowupstrbarriers_wetland_ha,
    a.bt_belowupstrbarriers_slopeclass03_waterbodies_km,
    a.bt_belowupstrbarriers_slopeclass03_km,
    a.bt_belowupstrbarriers_slopeclass05_km,
    a.bt_belowupstrbarriers_slopeclass08_km,
    a.bt_belowupstrbarriers_slopeclass15_km,
    a.bt_belowupstrbarriers_slopeclass22_km,
    a.bt_belowupstrbarriers_slopeclass30_km,
    array_to_string(a.barriers_ch_cm_co_pk_sk_dnstr, ';'::text) AS barriers_ch_cm_co_pk_sk_dnstr,
    a.ch_cm_co_pk_sk_network_km,
    a.ch_cm_co_pk_sk_stream_km,
    a.ch_cm_co_pk_sk_lakereservoir_ha,
    a.ch_cm_co_pk_sk_wetland_ha,
    a.ch_cm_co_pk_sk_slopeclass03_waterbodies_km,
    a.ch_cm_co_pk_sk_slopeclass03_km,
    a.ch_cm_co_pk_sk_slopeclass05_km,
    a.ch_cm_co_pk_sk_slopeclass08_km,
    a.ch_cm_co_pk_sk_slopeclass15_km,
    a.ch_cm_co_pk_sk_slopeclass22_km,
    a.ch_cm_co_pk_sk_slopeclass30_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_network_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_stream_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_lakereservoir_ha,
    a.ch_cm_co_pk_sk_belowupstrbarriers_wetland_ha,
    a.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_waterbodies_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass05_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass08_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass15_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass22_km,
    a.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass30_km,
    array_to_string(a.barriers_st_dnstr, ';'::text) AS barriers_st_dnstr,
    a.st_network_km,
    a.st_stream_km,
    a.st_lakereservoir_ha,
    a.st_wetland_ha,
    a.st_slopeclass03_waterbodies_km,
    a.st_slopeclass03_km,
    a.st_slopeclass05_km,
    a.st_slopeclass08_km,
    a.st_slopeclass15_km,
    a.st_slopeclass22_km,
    a.st_slopeclass30_km,
    a.st_belowupstrbarriers_network_km,
    a.st_belowupstrbarriers_stream_km,
    a.st_belowupstrbarriers_lakereservoir_ha,
    a.st_belowupstrbarriers_wetland_ha,
    a.st_belowupstrbarriers_slopeclass03_waterbodies_km,
    a.st_belowupstrbarriers_slopeclass03_km,
    a.st_belowupstrbarriers_slopeclass05_km,
    a.st_belowupstrbarriers_slopeclass08_km,
    a.st_belowupstrbarriers_slopeclass15_km,
    a.st_belowupstrbarriers_slopeclass22_km,
    a.st_belowupstrbarriers_slopeclass30_km,
    array_to_string(a.barriers_wct_dnstr, ';'::text) AS barriers_wct_dnstr,
    a.wct_network_km,
    a.wct_stream_km,
    a.wct_lakereservoir_ha,
    a.wct_wetland_ha,
    a.wct_slopeclass03_waterbodies_km,
    a.wct_slopeclass03_km,
    a.wct_slopeclass05_km,
    a.wct_slopeclass08_km,
    a.wct_slopeclass15_km,
    a.wct_slopeclass22_km,
    a.wct_slopeclass30_km,
    a.wct_belowupstrbarriers_network_km,
    a.wct_belowupstrbarriers_stream_km,
    a.wct_belowupstrbarriers_lakereservoir_ha,
    a.wct_belowupstrbarriers_wetland_ha,
    a.wct_belowupstrbarriers_slopeclass03_waterbodies_km,
    a.wct_belowupstrbarriers_slopeclass03_km,
    a.wct_belowupstrbarriers_slopeclass05_km,
    a.wct_belowupstrbarriers_slopeclass08_km,
    a.wct_belowupstrbarriers_slopeclass15_km,
    a.wct_belowupstrbarriers_slopeclass22_km,
    a.wct_belowupstrbarriers_slopeclass30_km,
    h.bt_spawning_km,
    h.bt_rearing_km,
    h.bt_spawningrearing_km,
    h.bt_spawning_belowupstrbarriers_km,
    h.bt_rearing_belowupstrbarriers_km,
    h.bt_spawningrearing_belowupstrbarriers_km,
    h.ch_spawning_km,
    h.ch_rearing_km,
    h.ch_spawningrearing_km,
    h.ch_spawning_belowupstrbarriers_km,
    h.ch_rearing_belowupstrbarriers_km,
    h.ch_spawningrearing_belowupstrbarriers_km,
    h.cm_spawning_km,
    h.cm_spawning_belowupstrbarriers_km,
    h.co_spawning_km,
    h.co_rearing_km,
    h.co_rearing_ha,
    h.co_spawningrearing_km,
    h.co_spawning_belowupstrbarriers_km,
    h.co_rearing_belowupstrbarriers_km,
    h.co_rearing_belowupstrbarriers_ha,
    h.co_spawningrearing_belowupstrbarriers_km,
    h.pk_spawning_km,
    h.pk_spawning_belowupstrbarriers_km,
    h.sk_spawning_km,
    h.sk_rearing_km,
    h.sk_rearing_ha,
    h.sk_spawningrearing_km,
    h.sk_spawning_belowupstrbarriers_km,
    h.sk_rearing_belowupstrbarriers_km,
    h.sk_rearing_belowupstrbarriers_ha,
    h.sk_spawningrearing_belowupstrbarriers_km,
    h.st_spawning_km,
    h.st_rearing_km,
    h.st_spawningrearing_km,
    h.st_spawning_belowupstrbarriers_km,
    h.st_rearing_belowupstrbarriers_km,
    h.st_spawningrearing_belowupstrbarriers_km,
    h.salmon_spawningrearing_km,
    h.salmon_spawningrearing_belowupstrbarriers_km,
    h.salmonsteelhead_spawningrearing_km,
    h.salmonsteelhead_spawningrearing_belowupstrbarriers_km,
    h.wct_spawning_km,
    h.wct_rearing_km,
    h.wct_spawningrearing_km,
    h.wct_spawning_belowupstrbarriers_km,
    h.wct_rearing_belowupstrbarriers_km,
    h.wct_spawningrearing_belowupstrbarriers_km,
    c.geom
   FROM ((((((((((bcfishpass.crossings c
     LEFT JOIN bcfishpass.crossings_dnstr_observations cdo ON ((c.aggregated_crossings_id = cdo.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.crossings_upstr_observations cuo ON ((c.aggregated_crossings_id = cuo.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.crossings_dnstr_crossings cd ON ((c.aggregated_crossings_id = cd.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.crossings_dnstr_barriers_anthropogenic ad ON ((c.aggregated_crossings_id = ad.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.crossings_upstr_barriers_anthropogenic au ON ((c.aggregated_crossings_id = au.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.crossings_upstr_barriers_per_model aum ON ((c.aggregated_crossings_id = aum.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.crossings_upstream_access a ON ((c.aggregated_crossings_id = a.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.crossings_upstream_habitat h ON ((c.aggregated_crossings_id = h.aggregated_crossings_id)))
     LEFT JOIN bcfishpass.streams s ON ((c.linear_feature_id = s.linear_feature_id)))
     LEFT JOIN whse_basemapping.dbm_mof_50k_grid t ON (public.st_intersects(c.geom, t.geom)))
  ORDER BY c.aggregated_crossings_id, s.downstream_route_measure
  WITH NO DATA;

COMMIT;
