-- below datasets are not guaranteed to exist

--drop materialized view if exists bcfishpass.crossings_admin;
--create materialized view bcfishpass.crossings_admin;
--SELECT DISTINCT ON (c.aggregated_crossings_id) -- some of the admin areas are not clean/distinct, make sure to select just one
--  c.aggregated_crossings_id,
--  rd.admin_area_abbreviation as abms_regional_district,
--  muni.admin_area_abbreviation as abms_municipality,
--  ir.english_name as clab_indian_reserve_name,
--  ir.band_name as clab_indian_reserve_band_name,
--  np.english_name as clab_national_park_name,
--  pp.protected_lands_name as bc_protected_lands_name,
--  pmbc.owner_type as pmbc_owner_type,
--  nr.region_org_unit_name as adm_nr_region,
--  nr.district_name as adm_nr_district
--FROM bcfishpass.crossings c
--LEFT OUTER JOIN whse_legal_admin_boundaries.abms_regional_districts_sp rd
--ON ST_Intersects(c.geom, rd.geom)
--LEFT OUTER JOIN whse_legal_admin_boundaries.abms_municipalities_sp muni
--ON ST_Intersects(c.geom, muni.geom)
--LEFT OUTER JOIN whse_admin_boundaries.adm_indian_reserves_bands_sp ir
--ON ST_Intersects(c.geom, ir.geom)
--LEFT OUTER JOIN whse_admin_boundaries.clab_national_parks np
--ON ST_Intersects(c.geom, np.geom)
--LEFT OUTER JOIN whse_tantalis.ta_park_ecores_pa_svw pp
--ON ST_Intersects(c.geom, pp.geom)
--LEFT OUTER JOIN whse_cadastre.pmbc_parcel_fabric_poly_svw pmbc
--ON ST_Intersects(c.geom, pmbc.geom)
--LEFT OUTER JOIN whse_admin_boundaries.adm_nr_districts_sp nr
--ON ST_Intersects(c.geom, pmbc.geom)
--ORDER BY c.aggregated_crossings_id, rd.admin_area_abbreviation, muni.admin_area_abbreviation, ir.english_name, pp.protected_lands_name, pmbc.owner_type, nr.district_name;