drop view if exists bcfishpass.wsg_crossing_summary_current cascade;

create view bcfishpass.wsg_crossing_summary_current as 
select
  s.model_run_id                          ,
  s.watershed_group_code                  ,
  s.crossing_feature_type                 ,
  s.n_crossings_total                     ,
  s.n_passable_total                      ,
  s.n_barriers_total                      ,
  s.n_potential_total                     ,
  s.n_unknown_total                       ,
  s.n_barriers_accessible_bt              ,
  s.n_potential_accessible_bt             ,
  s.n_unknown_accessible_bt               ,
  s.n_barriers_accessible_ch_cm_co_pk_sk  ,
  s.n_potential_accessible_ch_cm_co_pk_sk ,
  s.n_unknown_accessible_ch_cm_co_pk_sk   ,
  s.n_barriers_accessible_st              ,
  s.n_potential_accessible_st             ,
  s.n_unknown_accessible_st               ,
  s.n_barriers_accessible_wct             ,
  s.n_potential_accessible_wct            ,
  s.n_unknown_accessible_wct              ,
  s.n_barriers_habitat_bt                 ,
  s.n_potential_habitat_bt                ,
  s.n_unknown_habitat_bt                  ,
  s.n_barriers_habitat_ch                 ,
  s.n_potential_habitat_ch                ,
  s.n_unknown_habitat_ch                  ,
  s.n_barriers_habitat_cm                 ,
  s.n_potential_habitat_cm                ,
  s.n_unknown_habitat_cm                  ,
  s.n_barriers_habitat_co                 ,
  s.n_potential_habitat_co                ,
  s.n_unknown_habitat_co                  ,
  s.n_barriers_habitat_pk                 ,
  s.n_potential_habitat_pk                ,
  s.n_unknown_habitat_pk                  ,
  s.n_barriers_habitat_sk                 ,
  s.n_potential_habitat_sk                ,
  s.n_unknown_habitat_sk                  ,
  s.n_barriers_habitat_salmon             ,
  s.n_potential_habitat_salmon            ,
  s.n_unknown_habitat_salmon              ,
  s.n_barriers_habitat_st                 ,
  s.n_potential_habitat_st                ,
  s.n_unknown_habitat_st                  ,
  s.n_barriers_habitat_wct                ,
  s.n_potential_habitat_wct               ,
  s.n_unknown_habitat_wct                 
from bcfishpass.wsg_crossing_summary s
inner join bcfishpass.log l 
on s.model_run_id = l.model_run_id
where l.date_completed = (select date_completed from bcfishpass.log order by date_completed desc limit 1)
order by s.watershed_group_code, s.crossing_feature_type;


drop view if exists bcfishpass.wsg_crossing_summary_previous;

create view bcfishpass.wsg_crossing_summary_previous as
select
  s.model_run_id                          ,
  s.watershed_group_code                  ,
  s.crossing_feature_type                 ,
  s.n_crossings_total                     ,
  s.n_passable_total                      ,
  s.n_barriers_total                      ,
  s.n_potential_total                     ,
  s.n_unknown_total                       ,
  s.n_barriers_accessible_bt              ,
  s.n_potential_accessible_bt             ,
  s.n_unknown_accessible_bt               ,
  s.n_barriers_accessible_ch_cm_co_pk_sk  ,
  s.n_potential_accessible_ch_cm_co_pk_sk ,
  s.n_unknown_accessible_ch_cm_co_pk_sk   ,
  s.n_barriers_accessible_st              ,
  s.n_potential_accessible_st             ,
  s.n_unknown_accessible_st               ,
  s.n_barriers_accessible_wct             ,
  s.n_potential_accessible_wct            ,
  s.n_unknown_accessible_wct              ,
  s.n_barriers_habitat_bt                 ,
  s.n_potential_habitat_bt                ,
  s.n_unknown_habitat_bt                  ,
  s.n_barriers_habitat_ch                 ,
  s.n_potential_habitat_ch                ,
  s.n_unknown_habitat_ch                  ,
  s.n_barriers_habitat_cm                 ,
  s.n_potential_habitat_cm                ,
  s.n_unknown_habitat_cm                  ,
  s.n_barriers_habitat_co                 ,
  s.n_potential_habitat_co                ,
  s.n_unknown_habitat_co                  ,
  s.n_barriers_habitat_pk                 ,
  s.n_potential_habitat_pk                ,
  s.n_unknown_habitat_pk                  ,
  s.n_barriers_habitat_sk                 ,
  s.n_potential_habitat_sk                ,
  s.n_unknown_habitat_sk                  ,
  s.n_barriers_habitat_salmon             ,
  s.n_potential_habitat_salmon            ,
  s.n_unknown_habitat_salmon              ,
  s.n_barriers_habitat_st                 ,
  s.n_potential_habitat_st                ,
  s.n_unknown_habitat_st                  ,
  s.n_barriers_habitat_wct                ,
  s.n_potential_habitat_wct               ,
  s.n_unknown_habitat_wct
from bcfishpass.wsg_crossing_summary s
inner join bcfishpass.log l
on s.model_run_id = l.model_run_id
where l.date_completed = (select date_completed from bcfishpass.log order by date_completed desc offset 1 limit 1)
order by watershed_group_code;


create view bcfishpass.wsg_crossing_summary_diff as
select
  a.watershed_group_code                  ,
  a.crossing_feature_type                 ,
  a.n_crossings_total                     - b.n_crossings_total as n_crossings_total,
  a.n_passable_total                      - b.n_passable_total as n_passable_total,
  a.n_barriers_total                      - b.n_barriers_total as n_barriers_total,
  a.n_potential_total                     - b.n_potential_total as n_potential_total,
  a.n_unknown_total                       - b.n_unknown_total as n_unknown_total,
  a.n_barriers_accessible_bt              - b.n_barriers_accessible_bt as n_barriers_accessible_bt,
  a.n_potential_accessible_bt             - b.n_potential_accessible_bt as n_potential_accessible_bt,
  a.n_unknown_accessible_bt               - b.n_unknown_accessible_bt as n_unknown_accessible_bt,
  a.n_barriers_accessible_ch_cm_co_pk_sk  - b.n_barriers_accessible_ch_cm_co_pk_sk as n_barriers_accessible_ch_cm_co_pk_sk,
  a.n_potential_accessible_ch_cm_co_pk_sk - b.n_potential_accessible_ch_cm_co_pk_sk as n_potential_accessible_ch_cm_co_pk_sk,
  a.n_unknown_accessible_ch_cm_co_pk_sk   - b.n_unknown_accessible_ch_cm_co_pk_sk as n_unknown_accessible_ch_cm_co_pk_sk,
  a.n_barriers_accessible_st              - b.n_barriers_accessible_st as n_barriers_accessible_st,
  a.n_potential_accessible_st             - b.n_potential_accessible_st as n_potential_accessible_st,
  a.n_unknown_accessible_st               - b.n_unknown_accessible_st as n_unknown_accessible_st,
  a.n_barriers_accessible_wct             - b.n_barriers_accessible_wct as n_barriers_accessible_wct,
  a.n_potential_accessible_wct            - b.n_potential_accessible_wct as n_potential_accessible_wct,
  a.n_unknown_accessible_wct              - b.n_unknown_accessible_wct as n_unknown_accessible_wct,
  a.n_barriers_habitat_bt                 - b.n_barriers_habitat_bt as n_barriers_habitat_bt,
  a.n_potential_habitat_bt                - b.n_potential_habitat_bt as n_potential_habitat_bt,
  a.n_unknown_habitat_bt                  - b.n_unknown_habitat_bt as n_unknown_habitat_bt,
  a.n_barriers_habitat_ch                 - b.n_barriers_habitat_ch as n_barriers_habitat_ch,
  a.n_potential_habitat_ch                - b.n_potential_habitat_ch as n_potential_habitat_ch,
  a.n_unknown_habitat_ch                  - b.n_unknown_habitat_ch as n_unknown_habitat_ch,
  a.n_barriers_habitat_cm                 - b.n_barriers_habitat_cm as n_barriers_habitat_cm,
  a.n_potential_habitat_cm                - b.n_potential_habitat_cm as n_potential_habitat_cm,
  a.n_unknown_habitat_cm                  - b.n_unknown_habitat_cm as n_unknown_habitat_cm,
  a.n_barriers_habitat_co                 - b.n_barriers_habitat_co as n_barriers_habitat_co,
  a.n_potential_habitat_co                - b.n_potential_habitat_co as n_potential_habitat_co,
  a.n_unknown_habitat_co                  - b.n_unknown_habitat_co as n_unknown_habitat_co,
  a.n_barriers_habitat_pk                 - b.n_barriers_habitat_pk as n_barriers_habitat_pk,
  a.n_potential_habitat_pk                - b.n_potential_habitat_pk as n_potential_habitat_pk,
  a.n_unknown_habitat_pk                  - b.n_unknown_habitat_pk as n_unknown_habitat_pk,
  a.n_barriers_habitat_sk                 - b.n_barriers_habitat_sk as n_barriers_habitat_sk,
  a.n_potential_habitat_sk                - b.n_potential_habitat_sk as n_potential_habitat_sk,
  a.n_unknown_habitat_sk                  - b.n_unknown_habitat_sk as n_unknown_habitat_sk,
  a.n_barriers_habitat_salmon             - b.n_barriers_habitat_salmon as n_barriers_habitat_salmon,
  a.n_potential_habitat_salmon            - b.n_potential_habitat_salmon as n_potential_habitat_salmon,
  a.n_unknown_habitat_salmon              - b.n_unknown_habitat_salmon as n_unknown_habitat_salmon,
  a.n_barriers_habitat_st                 - b.n_barriers_habitat_st as n_barriers_habitat_st,
  a.n_potential_habitat_st                - b.n_potential_habitat_st as n_potential_habitat_st,
  a.n_unknown_habitat_st                  - b.n_unknown_habitat_st as n_unknown_habitat_st,
  a.n_barriers_habitat_wct                - b.n_barriers_habitat_wct as n_barriers_habitat_wct,
  a.n_potential_habitat_wct               - b.n_potential_habitat_wct as n_potential_habitat_wct,
  a.n_unknown_habitat_wct                - b.n_unknown_habitat_wct as n_unknown_habitat_wct
from bcfishpass.wsg_crossing_summary_current a
inner join bcfishpass.wsg_crossing_summary_previous b
  on a.watershed_group_code = b.watershed_group_code
  and a.crossing_feature_type = b.crossing_feature_type
order by a.watershed_group_code;