drop view if exists bcfishpass.wsg_linear_summary_current;
create view bcfishpass.wsg_linear_summary_current as 
select distinct on (watershed_group_code)
  s.model_run_id                                             ,
  s.watershed_group_code                                     ,
  s.length_total                                             ,
  s.length_potentiallyaccessible_bt                          ,
  s.length_potentiallyaccessible_bt_observed                 ,
  s.length_potentiallyaccessible_bt_accessible_a             ,
  s.length_potentiallyaccessible_bt_accessible_b             ,
  s.length_obsrvd_spawning_rearing_bt                        ,
  s.length_obsrvd_spawning_rearing_bt_accessible_a           ,
  s.length_obsrvd_spawning_rearing_bt_accessible_b           ,
  s.length_spawning_rearing_bt                               ,
  s.length_spawning_rearing_bt_accessible_a                  ,
  s.length_spawning_rearing_bt_accessible_b                  ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk              ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk_observed     ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_a ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_b ,
  s.length_obsrvd_spawning_rearing_ch                        ,
  s.length_obsrvd_spawning_rearing_ch_accessible_a           ,
  s.length_obsrvd_spawning_rearing_ch_accessible_b           ,
  s.length_spawning_rearing_ch                               ,
  s.length_spawning_rearing_ch_accessible_a                  ,
  s.length_spawning_rearing_ch_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_cm                        ,
  s.length_obsrvd_spawning_rearing_cm_accessible_a           ,
  s.length_obsrvd_spawning_rearing_cm_accessible_b           ,
  s.length_spawning_rearing_cm                               ,
  s.length_spawning_rearing_cm_accessible_a                  ,
  s.length_spawning_rearing_cm_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_co                        ,
  s.length_obsrvd_spawning_rearing_co_accessible_a           ,
  s.length_obsrvd_spawning_rearing_co_accessible_b           ,
  s.length_spawning_rearing_co                               ,
  s.length_spawning_rearing_co_accessible_a                  ,
  s.length_spawning_rearing_co_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_pk                        ,
  s.length_obsrvd_spawning_rearing_pk_accessible_a           ,
  s.length_obsrvd_spawning_rearing_pk_accessible_b           ,
  s.length_spawning_rearing_pk                               ,
  s.length_spawning_rearing_pk_accessible_a                  ,
  s.length_spawning_rearing_pk_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_sk                        ,
  s.length_obsrvd_spawning_rearing_sk_accessible_a           ,
  s.length_obsrvd_spawning_rearing_sk_accessible_b           ,
  s.length_spawning_rearing_sk                               ,
  s.length_spawning_rearing_sk_accessible_a                  ,
  s.length_spawning_rearing_sk_accessible_b                  ,
  s.length_potentiallyaccessible_st                          ,
  s.length_potentiallyaccessible_st_observed                 ,
  s.length_potentiallyaccessible_st_accessible_a             ,
  s.length_potentiallyaccessible_st_accessible_b             ,
  s.length_obsrvd_spawning_rearing_st                        ,
  s.length_obsrvd_spawning_rearing_st_accessible_a           ,
  s.length_obsrvd_spawning_rearing_st_accessible_b           ,
  s.length_spawning_rearing_st                               ,
  s.length_spawning_rearing_st_accessible_a                  ,
  s.length_spawning_rearing_st_accessible_b                  ,
  s.length_potentiallyaccessible_wct                         ,
  s.length_potentiallyaccessible_wct_observed                ,
  s.length_potentiallyaccessible_wct_accessible_a            ,
  s.length_potentiallyaccessible_wct_accessible_b            ,
  s.length_obsrvd_spawning_rearing_wct                       ,
  s.length_obsrvd_spawning_rearing_wct_accessible_a          ,
  s.length_obsrvd_spawning_rearing_wct_accessible_b          ,
  s.length_spawning_rearing_wct                              ,
  s.length_spawning_rearing_wct_accessible_a                 ,
  s.length_spawning_rearing_wct_accessible_b
from bcfishpass.wsg_linear_summary s
inner join bcfishpass.log l 
on s.model_run_id = l.model_run_id
order by s.watershed_group_code, l.date_completed desc;


drop view if exists bcfishpass.wsg_linear_summary_previous;
create view bcfishpass.wsg_linear_summary_previous as
select
  s.model_run_id                                           ,
  s.watershed_group_code                                     ,
  s.length_total                                             ,
  s.length_potentiallyaccessible_bt                          ,
  s.length_potentiallyaccessible_bt_observed                 ,
  s.length_potentiallyaccessible_bt_accessible_a             ,
  s.length_potentiallyaccessible_bt_accessible_b             ,
  s.length_obsrvd_spawning_rearing_bt                        ,
  s.length_obsrvd_spawning_rearing_bt_accessible_a           ,
  s.length_obsrvd_spawning_rearing_bt_accessible_b           ,
  s.length_spawning_rearing_bt                               ,
  s.length_spawning_rearing_bt_accessible_a                  ,
  s.length_spawning_rearing_bt_accessible_b                  ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk              ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk_observed     ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_a ,
  s.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_b ,
  s.length_obsrvd_spawning_rearing_ch                        ,
  s.length_obsrvd_spawning_rearing_ch_accessible_a           ,
  s.length_obsrvd_spawning_rearing_ch_accessible_b           ,
  s.length_spawning_rearing_ch                               ,
  s.length_spawning_rearing_ch_accessible_a                  ,
  s.length_spawning_rearing_ch_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_cm                        ,
  s.length_obsrvd_spawning_rearing_cm_accessible_a           ,
  s.length_obsrvd_spawning_rearing_cm_accessible_b           ,
  s.length_spawning_rearing_cm                               ,
  s.length_spawning_rearing_cm_accessible_a                  ,
  s.length_spawning_rearing_cm_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_co                        ,
  s.length_obsrvd_spawning_rearing_co_accessible_a           ,
  s.length_obsrvd_spawning_rearing_co_accessible_b           ,
  s.length_spawning_rearing_co                               ,
  s.length_spawning_rearing_co_accessible_a                  ,
  s.length_spawning_rearing_co_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_pk                        ,
  s.length_obsrvd_spawning_rearing_pk_accessible_a           ,
  s.length_obsrvd_spawning_rearing_pk_accessible_b           ,
  s.length_spawning_rearing_pk                               ,
  s.length_spawning_rearing_pk_accessible_a                  ,
  s.length_spawning_rearing_pk_accessible_b                  ,
  s.length_obsrvd_spawning_rearing_sk                        ,
  s.length_obsrvd_spawning_rearing_sk_accessible_a           ,
  s.length_obsrvd_spawning_rearing_sk_accessible_b           ,
  s.length_spawning_rearing_sk                               ,
  s.length_spawning_rearing_sk_accessible_a                  ,
  s.length_spawning_rearing_sk_accessible_b                  ,
  s.length_potentiallyaccessible_st                          ,
  s.length_potentiallyaccessible_st_observed                 ,
  s.length_potentiallyaccessible_st_accessible_a             ,
  s.length_potentiallyaccessible_st_accessible_b             ,
  s.length_obsrvd_spawning_rearing_st                        ,
  s.length_obsrvd_spawning_rearing_st_accessible_a           ,
  s.length_obsrvd_spawning_rearing_st_accessible_b           ,
  s.length_spawning_rearing_st                               ,
  s.length_spawning_rearing_st_accessible_a                  ,
  s.length_spawning_rearing_st_accessible_b                  ,
  s.length_potentiallyaccessible_wct                         ,
  s.length_potentiallyaccessible_wct_observed                ,
  s.length_potentiallyaccessible_wct_accessible_a            ,
  s.length_potentiallyaccessible_wct_accessible_b            ,
  s.length_obsrvd_spawning_rearing_wct                       ,
  s.length_obsrvd_spawning_rearing_wct_accessible_a          ,
  s.length_obsrvd_spawning_rearing_wct_accessible_b          ,
  s.length_spawning_rearing_wct                              ,
  s.length_spawning_rearing_wct_accessible_a                 ,
  s.length_spawning_rearing_wct_accessible_b
from bcfishpass.wsg_linear_summary s
inner join bcfishpass.log l
on s.model_run_id = l.model_run_id
where l.date_completed = (select date_completed from bcfishpass.log order by date_completed desc offset 1 limit 1)
order by watershed_group_code;

drop view if exists bcfishpass.wsg_linear_summary_diff;
create view bcfishpass.wsg_linear_summary_diff as
select
  a.watershed_group_code                                     ,
  a.length_total                                             - b.length_total                                             as length_total,
  a.length_potentiallyaccessible_bt                          - b.length_potentiallyaccessible_bt                          as length_potentiallyaccessible_bt,
  a.length_potentiallyaccessible_bt_observed                 - b.length_potentiallyaccessible_bt_observed                 as length_potentiallyaccessible_bt_observed,
  a.length_potentiallyaccessible_bt_accessible_a             - b.length_potentiallyaccessible_bt_accessible_a             as length_potentiallyaccessible_bt_accessible_a,
  a.length_potentiallyaccessible_bt_accessible_b             - b.length_potentiallyaccessible_bt_accessible_b             as length_potentiallyaccessible_bt_accessible_b,
  a.length_obsrvd_spawning_rearing_bt                        - b.length_obsrvd_spawning_rearing_bt                        as length_obsrvd_spawning_rearing_bt,
  a.length_obsrvd_spawning_rearing_bt_accessible_a           - b.length_obsrvd_spawning_rearing_bt_accessible_a           as length_obsrvd_spawning_rearing_bt_accessible_a,
  a.length_obsrvd_spawning_rearing_bt_accessible_b           - b.length_obsrvd_spawning_rearing_bt_accessible_b           as length_obsrvd_spawning_rearing_bt_accessible_b,
  a.length_spawning_rearing_bt                               - b.length_spawning_rearing_bt                               as length_spawning_rearing_bt,
  a.length_spawning_rearing_bt_accessible_a                  - b.length_spawning_rearing_bt_accessible_a                  as length_spawning_rearing_bt_accessible_a,
  a.length_spawning_rearing_bt_accessible_b                  - b.length_spawning_rearing_bt_accessible_b                  as length_spawning_rearing_bt_accessible_b,
  a.length_potentiallyaccessible_ch_cm_co_pk_sk              - b.length_potentiallyaccessible_ch_cm_co_pk_sk              as length_potentiallyaccessible_ch_cm_co_pk_sk,
  a.length_potentiallyaccessible_ch_cm_co_pk_sk_observed     - b.length_potentiallyaccessible_ch_cm_co_pk_sk_observed     as length_potentiallyaccessible_ch_cm_co_pk_sk_observed,
  a.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_a - b.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_a as length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_a,
  a.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_b - b.length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_b as length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_b,
  a.length_obsrvd_spawning_rearing_ch                        - b.length_obsrvd_spawning_rearing_ch                        as length_obsrvd_spawning_rearing_ch,
  a.length_obsrvd_spawning_rearing_ch_accessible_a           - b.length_obsrvd_spawning_rearing_ch_accessible_a           as length_obsrvd_spawning_rearing_ch_accessible_a,
  a.length_obsrvd_spawning_rearing_ch_accessible_b           - b.length_obsrvd_spawning_rearing_ch_accessible_b           as length_obsrvd_spawning_rearing_ch_accessible_b,
  a.length_spawning_rearing_ch                               - b.length_spawning_rearing_ch                               as length_spawning_rearing_ch,
  a.length_spawning_rearing_ch_accessible_a                  - b.length_spawning_rearing_ch_accessible_a                  as length_spawning_rearing_ch_accessible_a,
  a.length_spawning_rearing_ch_accessible_b                  - b.length_spawning_rearing_ch_accessible_b                  as length_spawning_rearing_ch_accessible_b,
  a.length_obsrvd_spawning_rearing_cm                        - b.length_obsrvd_spawning_rearing_cm                        as length_obsrvd_spawning_rearing_cm,
  a.length_obsrvd_spawning_rearing_cm_accessible_a           - b.length_obsrvd_spawning_rearing_cm_accessible_a           as length_obsrvd_spawning_rearing_cm_accessible_a,
  a.length_obsrvd_spawning_rearing_cm_accessible_b           - b.length_obsrvd_spawning_rearing_cm_accessible_b           as length_obsrvd_spawning_rearing_cm_accessible_b,
  a.length_spawning_rearing_cm                               - b.length_spawning_rearing_cm                               as length_spawning_rearing_cm,
  a.length_spawning_rearing_cm_accessible_a                  - b.length_spawning_rearing_cm_accessible_a                  as length_spawning_rearing_cm_accessible_a,
  a.length_spawning_rearing_cm_accessible_b                  - b.length_spawning_rearing_cm_accessible_b                  as length_spawning_rearing_cm_accessible_b,
  a.length_obsrvd_spawning_rearing_co                        - b.length_obsrvd_spawning_rearing_co                        as length_obsrvd_spawning_rearing_co,
  a.length_obsrvd_spawning_rearing_co_accessible_a           - b.length_obsrvd_spawning_rearing_co_accessible_a           as length_obsrvd_spawning_rearing_co_accessible_a,
  a.length_obsrvd_spawning_rearing_co_accessible_b           - b.length_obsrvd_spawning_rearing_co_accessible_b           as length_obsrvd_spawning_rearing_co_accessible_b,
  a.length_spawning_rearing_co                               - b.length_spawning_rearing_co                               as length_spawning_rearing_co,
  a.length_spawning_rearing_co_accessible_a                  - b.length_spawning_rearing_co_accessible_a                  as length_spawning_rearing_co_accessible_a,
  a.length_spawning_rearing_co_accessible_b                  - b.length_spawning_rearing_co_accessible_b                  as length_spawning_rearing_co_accessible_b,
  a.length_obsrvd_spawning_rearing_pk                        - b.length_obsrvd_spawning_rearing_pk                        as length_obsrvd_spawning_rearing_pk,
  a.length_obsrvd_spawning_rearing_pk_accessible_a           - b.length_obsrvd_spawning_rearing_pk_accessible_a           as length_obsrvd_spawning_rearing_pk_accessible_a,
  a.length_obsrvd_spawning_rearing_pk_accessible_b           - b.length_obsrvd_spawning_rearing_pk_accessible_b           as length_obsrvd_spawning_rearing_pk_accessible_b,
  a.length_spawning_rearing_pk                               - b.length_spawning_rearing_pk                               as length_spawning_rearing_pk,
  a.length_spawning_rearing_pk_accessible_a                  - b.length_spawning_rearing_pk_accessible_a                  as length_spawning_rearing_pk_accessible_a,
  a.length_spawning_rearing_pk_accessible_b                  - b.length_spawning_rearing_pk_accessible_b                  as length_spawning_rearing_pk_accessible_b,
  a.length_obsrvd_spawning_rearing_sk                        - b.length_obsrvd_spawning_rearing_sk                        as length_obsrvd_spawning_rearing_sk,
  a.length_obsrvd_spawning_rearing_sk_accessible_a           - b.length_obsrvd_spawning_rearing_sk_accessible_a           as length_obsrvd_spawning_rearing_sk_accessible_a,
  a.length_obsrvd_spawning_rearing_sk_accessible_b           - b.length_obsrvd_spawning_rearing_sk_accessible_b           as length_obsrvd_spawning_rearing_sk_accessible_b,
  a.length_spawning_rearing_sk                               - b.length_spawning_rearing_sk                               as length_spawning_rearing_sk,
  a.length_spawning_rearing_sk_accessible_a                  - b.length_spawning_rearing_sk_accessible_a                  as length_spawning_rearing_sk_accessible_a,
  a.length_spawning_rearing_sk_accessible_b                  - b.length_spawning_rearing_sk_accessible_b                  as length_spawning_rearing_sk_accessible_b,
  a.length_potentiallyaccessible_st                          - b.length_potentiallyaccessible_st                          as length_potentiallyaccessible_st,
  a.length_potentiallyaccessible_st_observed                 - b.length_potentiallyaccessible_st_observed                 as length_potentiallyaccessible_st_observed,
  a.length_potentiallyaccessible_st_accessible_a             - b.length_potentiallyaccessible_st_accessible_a             as length_potentiallyaccessible_st_accessible_a,
  a.length_potentiallyaccessible_st_accessible_b             - b.length_potentiallyaccessible_st_accessible_b             as length_potentiallyaccessible_st_accessible_b,
  a.length_obsrvd_spawning_rearing_st                        - b.length_obsrvd_spawning_rearing_st                        as length_obsrvd_spawning_rearing_st,
  a.length_obsrvd_spawning_rearing_st_accessible_a           - b.length_obsrvd_spawning_rearing_st_accessible_a           as length_obsrvd_spawning_rearing_st_accessible_a,
  a.length_obsrvd_spawning_rearing_st_accessible_b           - b.length_obsrvd_spawning_rearing_st_accessible_b           as length_obsrvd_spawning_rearing_st_accessible_b,
  a.length_spawning_rearing_st                               - b.length_spawning_rearing_st                               as length_spawning_rearing_st,
  a.length_spawning_rearing_st_accessible_a                  - b.length_spawning_rearing_st_accessible_a                  as length_spawning_rearing_st_accessible_a,
  a.length_spawning_rearing_st_accessible_b                  - b.length_spawning_rearing_st_accessible_b                  as length_spawning_rearing_st_accessible_b,
  a.length_potentiallyaccessible_wct                         - b.length_potentiallyaccessible_wct                         as length_potentiallyaccessible_wct,
  a.length_potentiallyaccessible_wct_observed                - b.length_potentiallyaccessible_wct_observed                as length_potentiallyaccessible_wct_observed,
  a.length_potentiallyaccessible_wct_accessible_a            - b.length_potentiallyaccessible_wct_accessible_a            as length_potentiallyaccessible_wct_accessible_a,
  a.length_potentiallyaccessible_wct_accessible_b            - b.length_potentiallyaccessible_wct_accessible_b            as length_potentiallyaccessible_wct_accessible_b,
  a.length_obsrvd_spawning_rearing_wct                       - b.length_obsrvd_spawning_rearing_wct                       as length_obsrvd_spawning_rearing_wct,
  a.length_obsrvd_spawning_rearing_wct_accessible_a          - b.length_obsrvd_spawning_rearing_wct_accessible_a          as length_obsrvd_spawning_rearing_wct_accessible_a,
  a.length_obsrvd_spawning_rearing_wct_accessible_b          - b.length_obsrvd_spawning_rearing_wct_accessible_b          as length_obsrvd_spawning_rearing_wct_accessible_b,
  a.length_spawning_rearing_wct                              - b.length_spawning_rearing_wct                              as length_spawning_rearing_wct,
  a.length_spawning_rearing_wct_accessible_a                 - b.length_spawning_rearing_wct_accessible_a                 as length_spawning_rearing_wct_accessible_a,
  a.length_spawning_rearing_wct_accessible_b                 - b.length_spawning_rearing_wct_accessible_b                 as length_spawning_rearing_wct_accessible_b
from bcfishpass.wsg_linear_summary_current a
inner join bcfishpass.wsg_linear_summary_previous b
on a.watershed_group_code = b.watershed_group_code;