repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
  - repo: local
    hooks:
      - id: validate-plan-config
        name: Validate plan_config.yaml
        language: system
        entry: bash -c '$VIRTUAL_ENV/bin/python wcrp/scripts/validate_config.py'
        files: wcrp/plan_config\.yaml$