-- report on potentially accessible lengths and areas upstream, per species scenario / model
drop table if exists bcfishpass.crossings_upstream_access cascade;

create table bcfishpass.crossings_upstream_access (
  aggregated_crossings_id                                  text primary key,
  watershed_group_code                                     character varying (4),
  gradient                                                 double precision,
  total_network_km                                         double precision DEFAULT 0,
  total_stream_km                                          double precision DEFAULT 0,
  total_lakereservoir_ha                                   double precision DEFAULT 0,
  total_wetland_ha                                         double precision DEFAULT 0,
  total_slopeclass03_waterbodies_km                        double precision DEFAULT 0,
  total_slopeclass03_km                                    double precision DEFAULT 0,
  total_slopeclass05_km                                    double precision DEFAULT 0,
  total_slopeclass08_km                                    double precision DEFAULT 0,
  total_slopeclass15_km                                    double precision DEFAULT 0,
  total_slopeclass22_km                                    double precision DEFAULT 0,
  total_slopeclass30_km                                    double precision DEFAULT 0,
  total_belowupstrbarriers_network_km                      double precision DEFAULT 0,
  total_belowupstrbarriers_stream_km                       double precision DEFAULT 0,
  total_belowupstrbarriers_lakereservoir_ha                double precision DEFAULT 0,
  total_belowupstrbarriers_wetland_ha                      double precision DEFAULT 0,
  total_belowupstrbarriers_slopeclass03_waterbodies_km     double precision DEFAULT 0,
  total_belowupstrbarriers_slopeclass03_km                 double precision DEFAULT 0,
  total_belowupstrbarriers_slopeclass05_km                 double precision DEFAULT 0,
  total_belowupstrbarriers_slopeclass08_km                 double precision DEFAULT 0,
  total_belowupstrbarriers_slopeclass15_km                 double precision DEFAULT 0,
  total_belowupstrbarriers_slopeclass22_km                 double precision DEFAULT 0,
  total_belowupstrbarriers_slopeclass30_km                 double precision DEFAULT 0,
  
  barriers_bt_dnstr                                        text[],
  bt_network_km                                            double precision DEFAULT 0,
  bt_stream_km                                             double precision DEFAULT 0,
  bt_lakereservoir_ha                                      double precision DEFAULT 0,
  bt_wetland_ha                                            double precision DEFAULT 0,
  bt_slopeclass03_waterbodies_km                           double precision DEFAULT 0,
  bt_slopeclass03_km                                       double precision DEFAULT 0,
  bt_slopeclass05_km                                       double precision DEFAULT 0,
  bt_slopeclass08_km                                       double precision DEFAULT 0,
  bt_slopeclass15_km                                       double precision DEFAULT 0,
  bt_slopeclass22_km                                       double precision DEFAULT 0,
  bt_slopeclass30_km                                       double precision DEFAULT 0,
  bt_belowupstrbarriers_network_km                         double precision DEFAULT 0,
  bt_belowupstrbarriers_stream_km                          double precision DEFAULT 0,
  bt_belowupstrbarriers_lakereservoir_ha                   double precision DEFAULT 0,
  bt_belowupstrbarriers_wetland_ha                         double precision DEFAULT 0,
  bt_belowupstrbarriers_slopeclass03_waterbodies_km        double precision DEFAULT 0,
  bt_belowupstrbarriers_slopeclass03_km                    double precision DEFAULT 0,
  bt_belowupstrbarriers_slopeclass05_km                    double precision DEFAULT 0,
  bt_belowupstrbarriers_slopeclass08_km                    double precision DEFAULT 0,
  bt_belowupstrbarriers_slopeclass15_km                    double precision DEFAULT 0,
  bt_belowupstrbarriers_slopeclass22_km                    double precision DEFAULT 0,
  bt_belowupstrbarriers_slopeclass30_km                    double precision DEFAULT 0,
  
  barriers_ch_cm_co_pk_sk_dnstr                                  text[],
  ch_cm_co_pk_sk_network_km                                      double precision DEFAULT 0,
  ch_cm_co_pk_sk_stream_km                                       double precision DEFAULT 0,
  ch_cm_co_pk_sk_lakereservoir_ha                                double precision DEFAULT 0,
  ch_cm_co_pk_sk_wetland_ha                                      double precision DEFAULT 0,
  ch_cm_co_pk_sk_slopeclass03_waterbodies_km                     double precision DEFAULT 0,
  ch_cm_co_pk_sk_slopeclass03_km                                 double precision DEFAULT 0,
  ch_cm_co_pk_sk_slopeclass05_km                                 double precision DEFAULT 0,
  ch_cm_co_pk_sk_slopeclass08_km                                 double precision DEFAULT 0,
  ch_cm_co_pk_sk_slopeclass15_km                                 double precision DEFAULT 0,
  ch_cm_co_pk_sk_slopeclass22_km                                 double precision DEFAULT 0,
  ch_cm_co_pk_sk_slopeclass30_km                                 double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_network_km                   double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_stream_km                    double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_lakereservoir_ha             double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_wetland_ha                   double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_waterbodies_km  double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_km              double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_slopeclass05_km              double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_slopeclass08_km              double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_slopeclass15_km              double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_slopeclass22_km              double precision DEFAULT 0,
  ch_cm_co_pk_sk_belowupstrbarriers_slopeclass30_km              double precision DEFAULT 0,
  
  barriers_ct_dv_rb_dnstr                                        text[],
  ct_dv_rb_network_km                                            double precision DEFAULT 0,
  ct_dv_rb_stream_km                                             double precision DEFAULT 0,
  ct_dv_rb_lakereservoir_ha                                      double precision DEFAULT 0,
  ct_dv_rb_wetland_ha                                            double precision DEFAULT 0,
  ct_dv_rb_slopeclass03_waterbodies_km                           double precision DEFAULT 0,
  ct_dv_rb_slopeclass03_km                                       double precision DEFAULT 0,
  ct_dv_rb_slopeclass05_km                                       double precision DEFAULT 0,
  ct_dv_rb_slopeclass08_km                                       double precision DEFAULT 0,
  ct_dv_rb_slopeclass15_km                                       double precision DEFAULT 0,
  ct_dv_rb_slopeclass22_km                                       double precision DEFAULT 0,
  ct_dv_rb_slopeclass30_km                                       double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_network_km                         double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_stream_km                          double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_lakereservoir_ha                   double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_wetland_ha                         double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_slopeclass03_waterbodies_km        double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_slopeclass03_km                    double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_slopeclass05_km                    double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_slopeclass08_km                    double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_slopeclass15_km                    double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_slopeclass22_km                    double precision DEFAULT 0,
  ct_dv_rb_belowupstrbarriers_slopeclass30_km                    double precision DEFAULT 0,

  barriers_st_dnstr                                        text[],
  st_network_km                                            double precision DEFAULT 0,
  st_stream_km                                             double precision DEFAULT 0,
  st_lakereservoir_ha                                      double precision DEFAULT 0,
  st_wetland_ha                                            double precision DEFAULT 0,
  st_slopeclass03_waterbodies_km                           double precision DEFAULT 0,
  st_slopeclass03_km                                       double precision DEFAULT 0,
  st_slopeclass05_km                                       double precision DEFAULT 0,
  st_slopeclass08_km                                       double precision DEFAULT 0,
  st_slopeclass15_km                                       double precision DEFAULT 0,
  st_slopeclass22_km                                       double precision DEFAULT 0,
  st_slopeclass30_km                                       double precision DEFAULT 0,
  st_belowupstrbarriers_network_km                         double precision DEFAULT 0,
  st_belowupstrbarriers_stream_km                          double precision DEFAULT 0,
  st_belowupstrbarriers_lakereservoir_ha                   double precision DEFAULT 0,
  st_belowupstrbarriers_wetland_ha                         double precision DEFAULT 0,
  st_belowupstrbarriers_slopeclass03_waterbodies_km        double precision DEFAULT 0,
  st_belowupstrbarriers_slopeclass03_km                    double precision DEFAULT 0,
  st_belowupstrbarriers_slopeclass05_km                    double precision DEFAULT 0,
  st_belowupstrbarriers_slopeclass08_km                    double precision DEFAULT 0,
  st_belowupstrbarriers_slopeclass15_km                    double precision DEFAULT 0,
  st_belowupstrbarriers_slopeclass22_km                    double precision DEFAULT 0,
  st_belowupstrbarriers_slopeclass30_km                    double precision DEFAULT 0,
  
  barriers_wct_dnstr                                       text[],
  wct_network_km                                           double precision DEFAULT 0,
  wct_stream_km                                            double precision DEFAULT 0,
  wct_lakereservoir_ha                                     double precision DEFAULT 0,
  wct_wetland_ha                                           double precision DEFAULT 0,
  wct_slopeclass03_waterbodies_km                          double precision DEFAULT 0,
  wct_slopeclass03_km                                      double precision DEFAULT 0,
  wct_slopeclass05_km                                      double precision DEFAULT 0,
  wct_slopeclass08_km                                      double precision DEFAULT 0,
  wct_slopeclass15_km                                      double precision DEFAULT 0,
  wct_slopeclass22_km                                      double precision DEFAULT 0,
  wct_slopeclass30_km                                      double precision DEFAULT 0,
  wct_belowupstrbarriers_network_km                        double precision DEFAULT 0,
  wct_belowupstrbarriers_stream_km                         double precision DEFAULT 0,
  wct_belowupstrbarriers_lakereservoir_ha                  double precision DEFAULT 0,
  wct_belowupstrbarriers_wetland_ha                        double precision DEFAULT 0,
  wct_belowupstrbarriers_slopeclass03_waterbodies_km       double precision DEFAULT 0,
  wct_belowupstrbarriers_slopeclass03_km                   double precision DEFAULT 0,
  wct_belowupstrbarriers_slopeclass05_km                   double precision DEFAULT 0,
  wct_belowupstrbarriers_slopeclass08_km                   double precision DEFAULT 0,
  wct_belowupstrbarriers_slopeclass15_km                   double precision DEFAULT 0,
  wct_belowupstrbarriers_slopeclass22_km                   double precision DEFAULT 0,
  wct_belowupstrbarriers_slopeclass30_km                   double precision DEFAULT 0
 );