--do not generally drop or truncate this table - we want to retain this data
--drop table bcfishpass.log cascade;
--truncate bcfishpass.log cascade;
create table if not exists bcfishpass.log (
  model_run_id serial primary key,
  model_type text not null,
  date_completed timestamp not null default CURRENT_TIMESTAMP,
  git_id bytea not null,
  check (model_type in ('LINEAR','LATERAL'))
);

-- usage:
-- insert into bcfishpass.log (model_type, git_id) values ('LINEAR', decode('feac3689cef93cc02a4cb4ac6a0fdadebe980f4d', 'hex')) RETURNING model_run_id;

create table bcfishpass.wsg_linear_summary (
 model_run_id                                             integer references bcfishpass.log(model_run_id),
 watershed_group_code                                     text,
 length_total                                             numeric,
 length_potentiallyaccessible_bt                          numeric,
 length_potentiallyaccessible_bt_observed                 numeric,
 length_potentiallyaccessible_bt_accessible_a             numeric,
 length_potentiallyaccessible_bt_accessible_b             numeric,
 length_obsrvd_spawning_rearing_bt                        numeric,
 length_obsrvd_spawning_rearing_bt_accessible_a           numeric,
 length_obsrvd_spawning_rearing_bt_accessible_b           numeric,
 length_spawning_rearing_bt                               numeric,
 length_spawning_rearing_bt_accessible_a                  numeric,
 length_spawning_rearing_bt_accessible_b                  numeric,
 length_potentiallyaccessible_ch_cm_co_pk_sk              numeric,
 length_potentiallyaccessible_ch_cm_co_pk_sk_observed     numeric,
 length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_a numeric,
 length_potentiallyaccessible_ch_cm_co_pk_sk_accessible_b numeric,
 length_obsrvd_spawning_rearing_ch                        numeric,
 length_obsrvd_spawning_rearing_ch_accessible_a           numeric,
 length_obsrvd_spawning_rearing_ch_accessible_b           numeric,
 length_spawning_rearing_ch                               numeric,
 length_spawning_rearing_ch_accessible_a                  numeric,
 length_spawning_rearing_ch_accessible_b                  numeric,
 length_obsrvd_spawning_rearing_cm                        numeric,
 length_obsrvd_spawning_rearing_cm_accessible_a           numeric,
 length_obsrvd_spawning_rearing_cm_accessible_b           numeric,
 length_spawning_rearing_cm                               numeric,
 length_spawning_rearing_cm_accessible_a                  numeric,
 length_spawning_rearing_cm_accessible_b                  numeric,
 length_obsrvd_spawning_rearing_co                        numeric,
 length_obsrvd_spawning_rearing_co_accessible_a           numeric,
 length_obsrvd_spawning_rearing_co_accessible_b           numeric,
 length_spawning_rearing_co                               numeric,
 length_spawning_rearing_co_accessible_a                  numeric,
 length_spawning_rearing_co_accessible_b                  numeric,
 length_obsrvd_spawning_rearing_pk                        numeric,
 length_obsrvd_spawning_rearing_pk_accessible_a           numeric,
 length_obsrvd_spawning_rearing_pk_accessible_b           numeric,
 length_spawning_rearing_pk                               numeric,
 length_spawning_rearing_pk_accessible_a                  numeric,
 length_spawning_rearing_pk_accessible_b                  numeric,
 length_obsrvd_spawning_rearing_sk                        numeric,
 length_obsrvd_spawning_rearing_sk_accessible_a           numeric,
 length_obsrvd_spawning_rearing_sk_accessible_b           numeric,
 length_spawning_rearing_sk                               numeric,
 length_spawning_rearing_sk_accessible_a                  numeric,
 length_spawning_rearing_sk_accessible_b                  numeric,
 length_potentiallyaccessible_st                          numeric,
 length_potentiallyaccessible_st_observed                 numeric,
 length_potentiallyaccessible_st_accessible_a             numeric,
 length_potentiallyaccessible_st_accessible_b             numeric,
 length_obsrvd_spawning_rearing_st                        numeric,
 length_obsrvd_spawning_rearing_st_accessible_a           numeric,
 length_obsrvd_spawning_rearing_st_accessible_b           numeric,
 length_spawning_rearing_st                               numeric,
 length_spawning_rearing_st_accessible_a                  numeric,
 length_spawning_rearing_st_accessible_b                  numeric,
 length_potentiallyaccessible_wct                         numeric,
 length_potentiallyaccessible_wct_observed                numeric,
 length_potentiallyaccessible_wct_accessible_a            numeric,
 length_potentiallyaccessible_wct_accessible_b            numeric,
 length_obsrvd_spawning_rearing_wct                       numeric,
 length_obsrvd_spawning_rearing_wct_accessible_a          numeric,
 length_obsrvd_spawning_rearing_wct_accessible_b          numeric,
 length_spawning_rearing_wct                              numeric,
 length_spawning_rearing_wct_accessible_a                 numeric,
 length_spawning_rearing_wct_accessible_b                 numeric
);

create table bcfishpass.wsg_crossing_summary (
  model_run_id                          integer references bcfishpass.log(model_run_id),
  watershed_group_code                  text,
  crossing_feature_type                 text,
  n_crossings_total                     integer,
  n_passable_total                      integer,
  n_barriers_total                      integer,
  n_potential_total                     integer,
  n_unknown_total                       integer,
  n_barriers_accessible_bt              integer,
  n_potential_accessible_bt             integer,
  n_unknown_accessible_bt               integer,
  n_barriers_accessible_ch_cm_co_pk_sk  integer,
  n_potential_accessible_ch_cm_co_pk_sk integer,
  n_unknown_accessible_ch_cm_co_pk_sk   integer,
  n_barriers_accessible_st              integer,
  n_potential_accessible_st             integer,
  n_unknown_accessible_st               integer,
  n_barriers_accessible_wct             integer,
  n_potential_accessible_wct            integer,
  n_unknown_accessible_wct              integer,
  n_barriers_habitat_bt                 integer,
  n_potential_habitat_bt                integer,
  n_unknown_habitat_bt                  integer,
  n_barriers_habitat_ch                 integer,
  n_potential_habitat_ch                integer,
  n_unknown_habitat_ch                  integer,
  n_barriers_habitat_cm                 integer,
  n_potential_habitat_cm                integer,
  n_unknown_habitat_cm                  integer,
  n_barriers_habitat_co                 integer,
  n_potential_habitat_co                integer,
  n_unknown_habitat_co                  integer,
  n_barriers_habitat_pk                 integer,
  n_potential_habitat_pk                integer,
  n_unknown_habitat_pk                  integer,
  n_barriers_habitat_sk                 integer,
  n_potential_habitat_sk                integer,
  n_unknown_habitat_sk                  integer,
  n_barriers_habitat_salmon             integer,
  n_potential_habitat_salmon            integer,
  n_unknown_habitat_salmon              integer,
  n_barriers_habitat_st                 integer,
  n_potential_habitat_st                integer,
  n_unknown_habitat_st                  integer,
  n_barriers_habitat_wct                integer,
  n_potential_habitat_wct               integer,
  n_unknown_habitat_wct                 integer
);