#!/bin/bash
set -euxo pipefail

#-------
# Process/refresh modelled crossings
#-------

# load latest data fixes to the db
mkdir .make
make --debug=basic .make/data

# build the crossings
cd model/01_access/modelled_stream_crossings
rm -Rf .make
rm -Rf data
make .make/modelled_stream_crossings --debug=basic