#!/bin/bash
set -euxo pipefail

#-------
# Process/refresh modelled crossings
#-------

# load latest data fixes to the db
make --debug=basic .make/data

# build the crossings
cd $PROJECTS/bcfishpass/model/01_access/modelled_stream_crossings
rm -Rf .make
rm -Rf data
make .make/modelled_stream_crossings --debug=basic

# dump to s3
ogr2ogr \
	-f GPKG \
	modelled_stream_crossings.gpkg \
	PG:$DATABASE_URL \
	-nlt PointZM \
	-nln modelled_stream_crossings \
	-sql "select \
		 modelled_crossing_id, \
		 modelled_crossing_type, \
		 array_to_string(modelled_crossing_type_source, '; ') as modelled_crossing_type_source, \
		 transport_line_id, \
		 ften_road_section_lines_id, \
		 og_road_segment_permit_id, \
		 og_petrlm_dev_rd_pre06_pub_id, \
		 railway_track_id, \
		 linear_feature_id, \
		 blue_line_key, \
		 downstream_route_measure, \
		 wscode_ltree, \
		 localcode_ltree, \
		 watershed_group_code, \
		 geom \
		from bcfishpass.modelled_stream_crossings"

sozip modelled_stream_crossings.gpkg.zip modelled_stream_crossings.gpkg
aws s3 cp modelled_stream_crossings.gpkg.zip s3://bcfishpass/modelled_stream_crossings_test.gpkg.zip

echo "Latest modelled crossings data now available at:"
echo "https://bcfishpass.s3.us-west-2.amazonaws.com/modelled_stream_crossings.gpkg.zip"