#!/bin/bash
set -euxo pipefail

#-------
# Process/refresh modelled crossings
#-------

# build the crossings
cd model/01_access/modelled_stream_crossings
rm -Rf .make
rm -Rf data
make .make/modelled_stream_crossings --debug=basic