#!/bin/bash
set -euxo pipefail

#-------
# Run the access model and habitat model
#-------

# run access model
cd model/01_access
./model_access_1.sh
./model_access_2.sh

# run habitat model
cd ../02_habitat_linear
./habitat_linear.sh