#!/bin/bash
set -euxo pipefail

#-------
# bcfishobs - link bc fish observations to FWA
#-------

git clone https://github.com/smnorris/bcfishobs
cd bcfishobs
mkdir -p .make
make -t .make/fiss_fish_obsrvtn_pnt_sp  # this is refreshed elsewhere
make --debug=basic