#!/bin/bash
set -euxo pipefail

#-------
# Prep access model
#-------

# load latest data fixes to the db
make --debug=basic .make/data

# already built
cd model/01_access
mkdir -p .make
make -t .make/gradient_barriers
make -t .make/modelled_stream_crossings

# build everything else
make .make/model_access_prep --debug=basic