#!/bin/bash
set -euxo pipefail

#-------
# download CABD dams and falls
#-------

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

$PSQL -c "truncate cabd.dams"
ogr2ogr -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  -nln cabd.dams \
  "https://cabd-web.azurewebsites.net/cabd-api/features/dams?filter=province_territory_code:eq:bc&filter=use_analysis:eq:true" \
  OGRGeoJSON

$PSQL -c "truncate cabd.waterfalls"
ogr2ogr -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  -nln cabd.waterfalls \
  "https://cabd-web.azurewebsites.net/cabd-api/features/waterfalls?filter=province_territory_code:eq:bc&filter=use_analysis:eq:true" \
  OGRGeoJSON  

# refresh views linking CABD features to FWA streams here?