#!/bin/bash
set -euxo pipefail

# connect to server, create tunnel for bcfishpass database connection

mkdir -p .ssh/
chmod 700 .ssh/
echo "$SSH_KEY" > .ssh/bcfishpass.key
chmod 600 .ssh/bcfishpass.key
cat <<EOF > .ssh/config
Host bcfishpass
  HostName $SSH_HOST
  User $SSH_USER
  ServerAliveInterval 60
  IdentityFile .ssh/bcfishpass.key
EOF
chmod 600 .ssh/config
ssh-keyscan -H $SSH_HOST >> .ssh/known_hosts
chmod 600 .ssh/known_hosts
nohup autossh -M 0 -N -L 63333:$DATABASE_HOST:5432 -F .ssh/config -o UserKnownHostsFile=.ssh/known_hosts bcfishpass &
sleep 5