#!/bin/bash
set -euxo pipefail

# connect to cabd processing server, create tunnel for bcfishpass database connection

apt-get update
apt-get install -y openssh-client
apt-get install -y autossh
mkdir -p .ssh/
chmod 700 .ssh/
echo "$SSH_KEY" > .ssh/cabd.key
chmod 600 .ssh/cabd.key
cat <<EOF > .ssh/config
Host cabd
  HostName $SSH_HOST
  User $SSH_USER
  IdentityFile .ssh/cabd.key
EOF
chmod 600 .ssh/config
ssh-keyscan -H $SSH_HOST >> .ssh/known_hosts
chmod 600 .ssh/known_hosts
nohup autossh -M 0 -N -L 63333:$DATABASE_HOST:5432 -F .ssh/config -o UserKnownHostsFile=.ssh/known_hosts cabd &
sleep 5