#!/bin/bash
set -euxo pipefail

# install required tools (azcli/azcopy/openssh/autossh)

curl -sL https://aka.ms/InstallAzureCLIDeb | bash
curl -sSL -O https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
apt-get update
apt-get install azcopy
apt-get install -y openssh-client
apt-get install -y autossh

# connect to cabd processing server, create tunnel for bcfishpass database connection

mkdir -p .ssh/
chmod 700 .ssh/
echo "$SSH_KEY" > .ssh/cabd.key
chmod 600 .ssh/cabd.key
cat <<EOF > .ssh/config
Host cabd
  HostName $SSH_HOST
  User $SSH_USER
  IdentityFile .ssh/cabd.key
EOF
chmod 600 .ssh/config
ssh-keyscan -H $SSH_HOST >> .ssh/known_hosts
chmod 600 .ssh/known_hosts
nohup autossh -M 0 -N -L 63333:$DATABASE_HOST:5432 -F .ssh/config -o UserKnownHostsFile=.ssh/known_hosts cabd &
sleep 5