#!/bin/bash
set -euxo pipefail

#-------
# monthly data refresh
#-------

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

# bcdata loads
# ----
jq -c '.[]' bcgw_sources.json | while read item; do
    schedule=$(jq -r '.schedule' <<< "$item")
    source=$(jq -r '.source' <<< "$item")
    if [ "$schedule" == "M" ] ; then
      echo "Loading $source from cache"

      # this can fail without an exit 1, capture stderr
      output=$(ogr2ogr -f PostgreSQL \
        "PG:$DATABASE_URL" \
        --config OGR_TRUNCATE=YES \
        -append \
        -preserve_fid \
        -nln $source \
        --config PG_USE_COPY=YES \
        /vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/$source.parquet \
        $source 2>&1)

        if [[ "$output" == *"ERROR"* ]]; then
          echo "Error detected in command output: $output"
          exit 1
        fi
    fi
done

# load DRA
ogr2ogr -f PostgreSQL \
  "PG:$DATABASE_URL" \
  --config OGR_TRUNCATE=YES \
  -append \
  -preserve_fid \
  -nln whse_basemapping.transport_line \
  --config PG_USE_COPY=YES \
  /vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/whse_basemapping.transport_line.parquet \
  whse_basemapping.transport_line

#-------
# refresh code tables - unlikely to change, but simple/quick to load
#-------
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_type_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_type_code

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_surface_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_surface_code

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_divided_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_divided_code

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_structure_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_structure_code



# parcel fabric, renaming download so it can be read without unzipping
# ----
curl \
  -o /tmp/pmbc_parcel_fabric_poly_svw.gdb.zip \
  https://pub.data.gov.bc.ca/datasets/4cf233c2-f020-4f7a-9b87-1923252fbc24/pmbc_parcel_fabric_poly_svw.zip

ogr2ogr \
   -f PostgreSQL \
   PG:$DATABASE_URL \
   --config PG_USE_COPY YES \
   -overwrite \
   -t_srs EPSG:3005 \
   -dim XY \
   -lco GEOMETRY_NAME=geom \
   -lco FID=PARCEL_FABRIC_POLY_ID \
   -nln bcdata.pmbc_parcel_fabric_poly_svw \
   /tmp/pmbc_parcel_fabric_poly_svw.gdb.zip \
   pmbc_parcel_fabric_poly_svw

# load to target & drop temp (note that schemas do not quite match)
$PSQL -c "truncate whse_cadastre.pmbc_parcel_fabric_poly_svw;
          insert into whse_cadastre.pmbc_parcel_fabric_poly_svw (
            parcel_fabric_poly_id ,
            parcel_name           ,
            plan_number           ,
            pin                   ,
            pid_number            ,
            parcel_status         ,
            parcel_class          ,
            owner_type            ,
            parcel_start_date     ,
            municipality          ,
            regional_district     ,
            when_updated          ,
            geom
          )
          select
            parcel_fabric_poly_id ,
            parcel_name           ,
            plan_number           ,
            pin                   ,
            pid                   ,
            parcel_status         ,
            parcel_class          ,
            owner_type            ,
            parcel_start_date     ,
            municipality          ,
            regional_district     ,
            when_updated          ,
            geom
          from bcdata.pmbc_parcel_fabric_poly_svw"
$PSQL -c "drop table bcdata.pmbc_parcel_fabric_poly_svw"

# additional processing
# ----
$PSQL -c "refresh materialized view bcdata.parks"
# range view is too resource intensive for some clients - schedule this job elsewhere
#$PSQL -c "refresh materialized view bcdata.ften_range_poly_carto_vw"



