#!/bin/bash
set -euxo pipefail

#-------
# weekly data refresh
#-------

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

# *note*
# weekly bcfishobs processing is scheduled via workflow bcfishobs repository

# bcdata loads
jq -c '.[]' bcgw_sources.json | while read item; do
    schedule=$(jq -r '.schedule' <<< "$item")
    source=$(jq -r '.source' <<< "$item")
    if [ "$schedule" == "W" ] ; then
      echo "Loading $source from cache"

      ogr2ogr -f PostgreSQL \
        "PG:$DATABASE_URL" \
        --config OGR_TRUNCATE=YES \
        -s_srs EPSG:4326 \
        -t_srs EPSG:3005 \
        -append \
        -preserve_fid \
        -nln $source \
        --config PG_USE_COPY=YES \
        /vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/$source.parquet \
        $source
    fi
done

# cabd
ogr2ogr -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE=YES \
  -nln cabd.dams \
  "https://cabd-web.azurewebsites.net/cabd-api/features/dams?filter=province_territory_code:eq:bc&filter=use_analysis:eq:true" \
  OGRGeoJSON

ogr2ogr -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE=YES \
  -nln cabd.waterfalls \
  "https://cabd-web.azurewebsites.net/cabd-api/features/waterfalls?filter=province_territory_code:eq:bc&filter=use_analysis:eq:true" \
  OGRGeoJSON
