#!/bin/bash
set -euxo pipefail

#-------
# monthly data refresh
#-------

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

# bcdata loads
# ----
bcdata bc2pg -r whse_admin_boundaries.clab_indian_reserves
bcdata bc2pg -r whse_admin_boundaries.clab_national_parks
bcdata bc2pg -r whse_basemapping.gba_local_reg_greenspaces_sp
bcdata bc2pg -r whse_basemapping.gba_railway_structure_lines_sp
bcdata bc2pg -r whse_basemapping.gba_railway_tracks_sp
bcdata bc2pg -r whse_basemapping.gba_transmission_lines_sp
bcdata bc2pg -r whse_basemapping.gns_geographical_names_sp
bcdata bc2pg -r whse_environmental_monitoring.envcan_hydrometric_stn_sp
bcdata bc2pg -r whse_fish.fiss_stream_sample_sites_sp
bcdata bc2pg -r whse_forest_tenure.ften_range_poly_svw
bcdata bc2pg -r whse_imagery_and_base_maps.mot_road_structure_sp
bcdata bc2pg -r whse_legal_admin_boundaries.abms_municipalities_sp
bcdata bc2pg -r whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp
bcdata bc2pg -r whse_tantalis.ta_conservancy_areas_svw
bcdata bc2pg -r whse_tantalis.ta_park_ecores_pa_svw
bcdata bc2pg -r whse_forest_tenure.ften_road_section_lines_svw
bcdata bc2pg -r whse_mineral_tenure.og_road_segment_permit_sp


# load DRA from object storage (with public portion of source transport_line schema)
$PSQL -c "drop table if exists bcdata.transport_line" # in case of any failed loads
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  --config PG_USE_COPY YES \
  -lco GEOMETRY_NAME=geom \
  -lco FID=transport_line_id \
  -nln bcdata.transport_line \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line
$PSQL -c "truncate whse_basemapping.transport_line;
          insert into whse_basemapping.transport_line
          (
            transport_line_id,
            custodian_partner_org,
            capture_date,
            data_capture_method_code,
            total_number_of_lanes,
            structured_name_1,
            structured_name_2,
            structured_name_3,
            structured_name_4,
            structured_name_5,
            highway_route_1,
            highway_exit_number,
            transport_line_type_code,
            transport_line_surface_code,
            transport_line_structure_code,
            geom
          )
          select
            transport_line_id,
            custodian_partner_org,
            capture_date,
            data_capture_method_code,
            total_number_of_lanes,
            structured_name_1,
            structured_name_2,
            structured_name_3,
            structured_name_4,
            structured_name_5,
            highway_route_1,
            highway_exit_number,
            transport_line_type_code,
            transport_line_surface_code,
            transport_line_structure_code,
            geom
      from bcdata.transport_line"
$PSQL -c "drop table bcdata.transport_line"

#-------
# refresh code tables - unlikely to change, but simple/quick to load
#-------
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_type_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_type_code

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_surface_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_surface_code

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_divided_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_divided_code

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE YES \
  -nln whse_basemapping.transport_line_structure_code \
  /vsizip//vsicurl/https://nrs.objectstore.gov.bc.ca/bchamp/bcdata/transport_line.gpkg.zip \
  transport_line_structure_code



# parcel fabric, renaming download so it can be read without unzipping
# ----
curl \
  -o /tmp/pmbc_parcel_fabric_poly_svw.gdb.zip \
  https://pub.data.gov.bc.ca/datasets/4cf233c2-f020-4f7a-9b87-1923252fbc24/pmbc_parcel_fabric_poly_svw.zip

ogr2ogr \
   -f PostgreSQL \
   PG:$DATABASE_URL \
   --config PG_USE_COPY YES \
   -overwrite \
   -t_srs EPSG:3005 \
   -dim XY \
   -lco GEOMETRY_NAME=geom \
   -lco FID=PARCEL_FABRIC_POLY_ID \
   -nln bcdata.pmbc_parcel_fabric_poly_svw \
   /tmp/pmbc_parcel_fabric_poly_svw.gdb.zip \
   pmbc_parcel_fabric_poly_svw

# load to target & drop temp (note that schemas do not quite match)
$PSQL -c "truncate whse_cadastre.pmbc_parcel_fabric_poly_svw;
          insert into whse_cadastre.pmbc_parcel_fabric_poly_svw (
            parcel_fabric_poly_id ,
            parcel_name           ,
            plan_number           ,
            pin                   ,
            pid_number            ,
            parcel_status         ,
            parcel_class          ,
            owner_type            ,
            parcel_start_date     ,
            municipality          ,
            regional_district     ,
            when_updated          ,
            geom
          )
          select
            parcel_fabric_poly_id ,
            parcel_name           ,
            plan_number           ,
            pin                   ,
            pid                   ,
            parcel_status         ,
            parcel_class          ,
            owner_type            ,
            parcel_start_date     ,
            municipality          ,
            regional_district     ,
            when_updated          ,
            geom
          from bcdata.pmbc_parcel_fabric_poly_svw"
$PSQL -c "drop table bcdata.pmbc_parcel_fabric_poly_svw"

# additional processing
# ----
$PSQL -c "refresh materialized view bcdata.parks"
# range view is too resource intensive for some clients - schedule this job elsewhere
#$PSQL -c "refresh materialized view bcdata.ften_range_poly_carto_vw"



