#!/bin/bash

set -euxo pipefail

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"
WSGS=$($PSQL -AXt -c "select watershed_group_code from whse_basemapping.fwa_watershed_groups_poly")


cd model/01_access/gradient_barriers
$PSQL -c "truncate bcfishpass.gradient_barriers"  # just in case a previous job failed
parallel $PSQL -f sql/gradient_barriers_load.sql -v wsg={1} ::: $WSGS