#!/bin/bash
set -euxo pipefail

#-------
# Prep access model
#-------

# refresh observations/dams/falls/pscis
$PSQL -c "refresh materialized view bcfishpass.observations_vw"
$PSQL -c "refresh materialized view bcfishpass.dams_vw"
$PSQL -c "refresh materialized view bcfishpass.falls_vw"
$PSQL -c "refresh materialized view bcfishpass.falls_upstr_anadromous_vw"

cd model/01_access/pscis; ./pscis.sh; cd ..

# build barriers/crossings and index
make .make/model_access_prep --debug=basic