#!/bin/bash

# Copyright 2024 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euxo pipefail

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

ogr2ogr \
    -f GPKG \
    freshwater_fish_habitat_accessibility_MODEL.gpkg \
    PG:$DATABASE_URL \
    -nln crossings \
    -nlt PointZM \
    -sql "select
            aggregated_crossings_id,
            stream_crossing_id,
            dam_id,
            user_barrier_anthropogenic_id,
            modelled_crossing_id,
            crossing_source,
            crossing_feature_type,
            pscis_status,
            crossing_type_code,
            crossing_subtype_code,
            modelled_crossing_type_source,
            barrier_status,
            pscis_road_name,
            pscis_stream_name,
            pscis_assessment_comment,
            pscis_assessment_date,
            pscis_final_score,
            transport_line_structured_name_1,
            transport_line_type_description,
            transport_line_surface_description,
            ften_forest_file_id,
            ften_file_type_description,
            ften_client_number,
            ften_client_name,
            ften_life_cycle_status_code,
            rail_track_name,
            rail_owner_name,
            rail_operator_english_name,
            ogc_proponent,
            dam_name,
            dam_height,
            dam_owner,
            dam_use,
            dam_operating_status,
            utm_zone,
            utm_easting,
            utm_northing,
            dbm_mof_50k_grid,
            linear_feature_id,
            blue_line_key,
            watershed_key,
            downstream_route_measure,
            wscode,
            localcode,
            watershed_group_code,
            gnis_stream_name,
            stream_order,
            stream_magnitude,
            observedspp_dnstr,
            observedspp_upstr,
            crossings_dnstr,
            barriers_anthropogenic_dnstr,
            barriers_anthropogenic_dnstr_count,
            barriers_anthropogenic_upstr,
            barriers_anthropogenic_upstr_count,
            barriers_anthropogenic_ch_cm_co_pk_sk_upstr,
            barriers_anthropogenic_ch_cm_co_pk_sk_upstr_count,
            barriers_anthropogenic_st_upstr,
            barriers_anthropogenic_st_upstr_count,
            gradient,
            total_network_km,
            total_stream_km,
            total_lakereservoir_ha,
            total_wetland_ha,
            total_slopeclass03_waterbodies_km,
            total_slopeclass03_km,
            total_slopeclass05_km,
            total_slopeclass08_km,
            total_slopeclass15_km,
            total_slopeclass22_km,
            total_slopeclass30_km,
            total_belowupstrbarriers_network_km,
            total_belowupstrbarriers_stream_km,
            total_belowupstrbarriers_lakereservoir_ha,
            total_belowupstrbarriers_wetland_ha,
            total_belowupstrbarriers_slopeclass03_waterbodies_km,
            total_belowupstrbarriers_slopeclass03_km,
            total_belowupstrbarriers_slopeclass05_km,
            total_belowupstrbarriers_slopeclass08_km,
            total_belowupstrbarriers_slopeclass15_km,
            total_belowupstrbarriers_slopeclass22_km,
            total_belowupstrbarriers_slopeclass30_km,
            barriers_ch_cm_co_pk_sk_dnstr,
            ch_cm_co_pk_sk_network_km,
            ch_cm_co_pk_sk_stream_km,
            ch_cm_co_pk_sk_lakereservoir_ha,
            ch_cm_co_pk_sk_wetland_ha,
            ch_cm_co_pk_sk_slopeclass03_waterbodies_km,
            ch_cm_co_pk_sk_slopeclass03_km,
            ch_cm_co_pk_sk_slopeclass05_km,
            ch_cm_co_pk_sk_slopeclass08_km,
            ch_cm_co_pk_sk_slopeclass15_km,
            ch_cm_co_pk_sk_slopeclass22_km,
            ch_cm_co_pk_sk_slopeclass30_km,
            ch_cm_co_pk_sk_belowupstrbarriers_network_km,
            ch_cm_co_pk_sk_belowupstrbarriers_stream_km,
            ch_cm_co_pk_sk_belowupstrbarriers_lakereservoir_ha,
            ch_cm_co_pk_sk_belowupstrbarriers_wetland_ha,
            ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_waterbodies_km,
            ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_km,
            ch_cm_co_pk_sk_belowupstrbarriers_slopeclass05_km,
            ch_cm_co_pk_sk_belowupstrbarriers_slopeclass08_km,
            ch_cm_co_pk_sk_belowupstrbarriers_slopeclass15_km,
            ch_cm_co_pk_sk_belowupstrbarriers_slopeclass22_km,
            ch_cm_co_pk_sk_belowupstrbarriers_slopeclass30_km,
            barriers_st_dnstr,
            st_network_km,
            st_stream_km,
            st_lakereservoir_ha,
            st_wetland_ha,
            st_slopeclass03_waterbodies_km,
            st_slopeclass03_km,
            st_slopeclass05_km,
            st_slopeclass08_km,
            st_slopeclass15_km,
            st_slopeclass22_km,
            st_slopeclass30_km,
            st_belowupstrbarriers_network_km,
            st_belowupstrbarriers_stream_km,
            st_belowupstrbarriers_lakereservoir_ha,
            st_belowupstrbarriers_wetland_ha,
            st_belowupstrbarriers_slopeclass03_waterbodies_km,
            st_belowupstrbarriers_slopeclass03_km,
            st_belowupstrbarriers_slopeclass05_km,
            st_belowupstrbarriers_slopeclass08_km,
            st_belowupstrbarriers_slopeclass15_km,
            st_belowupstrbarriers_slopeclass22_km,
            st_belowupstrbarriers_slopeclass30_km,
            geom
          FROM bcfishpass.crossings_vw"

ogr2ogr \
    -f GPKG \
    -append \
    -update \
    freshwater_fish_habitat_accessibility_MODEL.gpkg \
    PG:$DATABASE_URL \
    -nln barriers_salmon \
    -nlt PointZM \
    -sql "select
            barriers_ch_cm_co_pk_sk_id,
            barrier_type,
            barrier_name,
            linear_feature_id,
            blue_line_key,
            watershed_key,
            downstream_route_measure,
            wscode_ltree as wscode,
            localcode_ltree as localcode,
            watershed_group_code,
            total_network_km,
            geom
            from bcfishpass.barriers_ch_cm_co_pk_sk"

ogr2ogr \
    -f GPKG \
    -append \
    -update \
    freshwater_fish_habitat_accessibility_MODEL.gpkg \
    PG:$DATABASE_URL \
    -nln barriers_steelhead \
    -nlt PointZM \
    -sql "select
			 barriers_st_id,
			 barrier_type,
			 barrier_name,
			 linear_feature_id,
			 blue_line_key,
			 watershed_key,
			 downstream_route_measure,
			 wscode_ltree as wscode,
			 localcode_ltree as localcode,
			 watershed_group_code,
			 total_network_km,
			 geom
  		  from bcfishpass.barriers_st"

ogr2ogr \
    -f GPKG \
    -append \
    -update \
    freshwater_fish_habitat_accessibility_MODEL.gpkg \
    PG:$DATABASE_URL \
    -nln model_access \
    -nlt LineStringZM \
    -sql "select * from bcfishpass.freshwater_fish_habitat_accessibility_model_vw"

ogr2ogr \
    -f GPKG \
    -append \
    -update \
    freshwater_fish_habitat_accessibility_MODEL.gpkg \
    PG:$DATABASE_URL \
    -nln observations \
    -nlt PointZM \
    -sql "select
       observation_key,
       species_code,
       species_name,
       observation_date,
       agency_name,
       source,
       source_ref,
       activity_code,
       activity,
       life_stage_code,
       life_stage,
       acat_report_url,
       release,
       linear_feature_id,
       blue_line_key,
       downstream_route_measure,
       wscode,
       localcode,
       watershed_group_code,
       geom
     from bcfishpass.observations
     where species_code in ('CH','CM','CO','PK','SK','ST')"


# requires gdal >=3.7
sozip \
  freshwater_fish_habitat_accessibility_MODEL.gpkg.zip \
  freshwater_fish_habitat_accessibility_MODEL.gpkg

aws s3 cp freshwater_fish_habitat_accessibility_MODEL.gpkg.zip s3://bchamp --acl public-read


# release a draft/undocumented BT model as stopgap for BT users that are not covered by files provided by CWF release
# (ie, non salmon watersheds)
# distributing this from the primary bcfishpass files would be preferred but the CWF db has limited capacity for additional processing,
# it is good to be conservative with it for now
ogr2ogr \
  -f GPKG \
  bcfishpass_streams_bt.gpkg.zip \
  PG:$DATABASE_URL \
  --debug ON \
  -nln streams_bt \
  -sql "SELECT
  segmented_stream_id,
  linear_feature_id,
  edge_type,
  blue_line_key,
  watershed_key,
  watershed_group_code,
  downstream_route_measure,
  length_metre,
  waterbody_key,
  wscode::text as wscode,
  localcode::text as localcode,
  gnis_name,
  stream_order,
  stream_magnitude,
  gradient,
  feature_code,
  upstream_route_measure,
  upstream_area_ha,
  stream_order_parent,
  stream_order_max,
  map_upstream,
  channel_width,
  mad_m3s,
  barriers_anthropogenic_dnstr,
  barriers_pscis_dnstr,
  barriers_dams_dnstr,
  barriers_dams_hydro_dnstr,
  barriers_bt_dnstr,
  crossings_dnstr,
  dam_dnstr_ind,
  dam_hydro_dnstr_ind,
  remediated_dnstr_ind,
  observation_key_upstr,
  obsrvtn_species_codes_upstr,
  species_codes_dnstr,
  access,
  spawning,
  rearing,
  geom
FROM bcfishpass.streams_bt_vw"

ogr2ogr \
    -f GPKG \
    bcfishpass_crossings.gpkg.zip \
    PG:$DATABASE_URL \
    -nln crossings \
    -nlt PointZM \
    -sql "select * FROM bcfishpass.crossings_vw"

# dump also a basic top crossings report
# this is just a draft for now, aggregated spawn/rear columns
# should be added to crossings_vw for better ranking
psql $DATABASE_URL -c "SELECT 
 aggregated_crossings_id,
 stream_crossing_id,
 dam_id,
 user_barrier_anthropogenic_id,
 modelled_crossing_id,
 crossing_source,
 crossing_feature_type,
 pscis_status,
 crossing_type_code,
 crossing_subtype_code,
 modelled_crossing_type_source,
 barrier_status,
 pscis_road_name,
 pscis_stream_name,
 pscis_assessment_comment,
 pscis_assessment_date,
 pscis_final_score,
 transport_line_structured_name_1,
 transport_line_type_description,
 transport_line_surface_description,
 ften_forest_file_id,
 ften_road_section_id,
 ften_file_type_description,
 ften_client_number,
 ften_client_name,
 ften_life_cycle_status_code,
 ften_map_label,
 rail_track_name,
 rail_owner_name,
 rail_operator_english_name,
 ogc_proponent,
 dam_name,
 dam_height,
 dam_owner,
 dam_use,
 dam_operating_status,
 linear_feature_id,
 blue_line_key,
 watershed_key,
 downstream_route_measure,
 wscode,
 localcode,
 watershed_group_code,
 gnis_stream_name,
 stream_order,
 stream_magnitude,
 observedspp_dnstr,
 observedspp_upstr,
 crossings_dnstr,
 barriers_anthropogenic_dnstr_count,
 barriers_anthropogenic_upstr_count,
 barriers_anthropogenic_ch_cm_co_pk_sk_upstr_count,
 barriers_anthropogenic_st_upstr_count,
 barriers_ch_cm_co_pk_sk_dnstr,
 ch_cm_co_pk_sk_network_km,
 ch_cm_co_pk_sk_stream_km,
 ch_cm_co_pk_sk_lakereservoir_ha,
 ch_cm_co_pk_sk_wetland_ha,
 ch_cm_co_pk_sk_slopeclass03_waterbodies_km,
 ch_cm_co_pk_sk_slopeclass03_km,
 ch_cm_co_pk_sk_slopeclass05_km,
 ch_cm_co_pk_sk_slopeclass08_km,
 ch_cm_co_pk_sk_slopeclass15_km,
 ch_cm_co_pk_sk_slopeclass22_km,
 ch_cm_co_pk_sk_slopeclass30_km,
 ch_cm_co_pk_sk_belowupstrbarriers_network_km,
 ch_cm_co_pk_sk_belowupstrbarriers_stream_km,
 ch_cm_co_pk_sk_belowupstrbarriers_lakereservoir_ha,
 ch_cm_co_pk_sk_belowupstrbarriers_wetland_ha,
 ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_waterbodies_km,
 ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_km,
 ch_cm_co_pk_sk_belowupstrbarriers_slopeclass05_km,
 ch_cm_co_pk_sk_belowupstrbarriers_slopeclass08_km,
 ch_cm_co_pk_sk_belowupstrbarriers_slopeclass15_km,
 ch_cm_co_pk_sk_belowupstrbarriers_slopeclass22_km,
 ch_cm_co_pk_sk_belowupstrbarriers_slopeclass30_km,
 barriers_st_dnstr,
 st_network_km,
 st_stream_km,
 st_lakereservoir_ha,
 st_wetland_ha,
 st_slopeclass03_waterbodies_km,
 st_slopeclass03_km,
 st_slopeclass05_km,
 st_slopeclass08_km,
 st_slopeclass15_km,
 st_slopeclass22_km,
 st_slopeclass30_km,
 st_belowupstrbarriers_network_km,
 st_belowupstrbarriers_stream_km,
 st_belowupstrbarriers_lakereservoir_ha,
 st_belowupstrbarriers_wetland_ha,
 st_belowupstrbarriers_slopeclass03_waterbodies_km,
 st_belowupstrbarriers_slopeclass03_km,
 st_belowupstrbarriers_slopeclass05_km,
 st_belowupstrbarriers_slopeclass08_km,
 st_belowupstrbarriers_slopeclass15_km,
 st_belowupstrbarriers_slopeclass22_km,
 st_belowupstrbarriers_slopeclass30_km,
 ch_spawning_km,
 ch_rearing_km,
 ch_spawning_belowupstrbarriers_km,
 ch_rearing_belowupstrbarriers_km,
 cm_spawning_km,
 cm_spawning_belowupstrbarriers_km,
 co_spawning_km,
 co_rearing_km,
 co_rearing_ha,
 co_spawning_belowupstrbarriers_km,
 co_rearing_belowupstrbarriers_km,
 co_rearing_belowupstrbarriers_ha,
 pk_spawning_km,
 pk_spawning_belowupstrbarriers_km,
 sk_spawning_km,
 sk_rearing_km,
 sk_rearing_ha,
 sk_spawning_belowupstrbarriers_km,
 sk_rearing_belowupstrbarriers_km,
 sk_rearing_belowupstrbarriers_ha,
 st_spawning_km,
 st_rearing_km,
 st_spawning_belowupstrbarriers_km,
 st_rearing_belowupstrbarriers_km
FROM bcfishpass.crossings_vw
WHERE barrier_status in ('BARRIER','POTENTIAL')
AND (
 bt_network_km > 0 OR
 ch_cm_co_pk_sk_network_km > 0 OR 
 st_network_km > 0
)
order by co_spawning_km desc
limit 200" --csv > barriers_by_co_spawning_upstr.csv    

aws s3 cp bcfishpass_streams_bt.gpkg.zip s3://bchamp --acl public-read
aws s3 cp bcfishpass_crossings.gpkg.zip s3://bchamp --acl public-read