#!/bin/bash
set -euxo pipefail

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

#-------
# set up bcfishpass schema
#-------

for sql in db/bcfishpass/tables/*.sql ; do
  $PSQL -f "$sql"
done

for sql in db/bcfishpass/views/*.sql ; do
  $PSQL -f "$sql"
done

for sql in db/bcfishpass/functions/*.sql ; do
  $PSQL -f "$sql"
done

# load these as required in various environments
#for sql in db/bcfishpass/reports/*.sql ; do
#  $PSQL -f "$sql"
#done
