#!/bin/bash
set -euxo pipefail

ogr2ogr \
    -f GPKG \
    test.gpkg \
    PG:$DATABASE_URL \
    -nln crossings \
    -nlt PointZM \
    -sql "select *
          from bcfishpass.freshwater_fish_habitat_accessibility_model_crossings_vw
          limit 100"

ogr2ogr \
    -f GPKG \
    -append \
    -update \
    test.gpkg \
    PG:$DATABASE_URL \
    -nln barriers_salmon \
    -nlt PointZM \
    -sql "select
            barriers_ch_cm_co_pk_sk_id,
            barrier_type,
            barrier_name,
            linear_feature_id,
            blue_line_key,
            watershed_key,
            downstream_route_measure,
            wscode_ltree as wscode,
            localcode_ltree as localcode,
            watershed_group_code,
            total_network_km,
            geom
          from bcfishpass.barriers_ch_cm_co_pk_sk
          limit 100"

# requires gdal >=3.7
sozip \
  test.gpkg.zip \
  test.gpkg

aws s3 cp test.gpkg.zip s3://bcfishpass