create table if not exists bcfishpass.totals (
  date_processed timestamp without time zone,
  watershed_group_code text not null,
  total_network_km numeric default 0,
  ch_co_sk_network_km numeric default 0,
  st_network_km numeric default 0,
  wct_network_km numeric default 0,
  ch_spawning_km  numeric default 0,
  ch_rearing_km  numeric default 0,
  co_spawning_km  numeric default 0,
  co_rearing_km  numeric default 0,
  sk_spawning_km  numeric default 0,
  sk_rearing_km  numeric default 0,
  st_spawning_km  numeric default 0,
  st_rearing_km  numeric default 0,
  wct_spawning_km  numeric default 0,
  wct_rearing_km  numeric default 0,
  cm_spawning_km  numeric default 0,
  pk_spawning_km  numeric default 0,
  all_spawning_km numeric default 0,
  all_rearing_km  numeric default 0,
  all_spawningrearing_km numeric default 0,
PRIMARY KEY (date_processed, watershed_group_code)
);
