-- document the primary output products - crossings_vw and streams_vw

BEGIN;

-- crossings_vw

comment on column bcfishpass.crossings_vw.aggregated_crossings_id IS 'unique identifier for crossing, generated from stream_crossing_id, modelled_crossing_id + 1000000000, user_barrier_anthropogenic_id + 1200000000, cabd_id';
comment on column bcfishpass.crossings_vw.stream_crossing_id IS 'PSCIS stream crossing unique identifier';
comment on column bcfishpass.crossings_vw.dam_id IS 'BC Dams unique identifier';
comment on column bcfishpass.crossings_vw.user_barrier_anthropogenic_id IS 'User added misc anthropogenic barriers unique identifier';
comment on column bcfishpass.crossings_vw.modelled_crossing_id IS 'Modelled crossing unique identifier';
comment on column bcfishpass.crossings_vw.crossing_source IS 'Data source for the crossing, one of: {PSCIS,MODELLED CROSSINGS,CABD,MISC BARRIERS}';
comment on column bcfishpass.crossings_vw.pscis_status IS 'From PSCIS, the current_pscis_status of the crossing, one of: {ASSESSED,HABITAT CONFIRMATION,DESIGN,REMEDIATED}';
comment on column bcfishpass.crossings_vw.crossing_type_code IS 'Defines the type of crossing present at the location of the stream crossing. Acceptable types are: OBS = Open Bottom Structure CBS = Closed Bottom Structure OTHER = Crossing structure does not fit into the above categories. Eg: ford, wier';
comment on column bcfishpass.crossings_vw.crossing_subtype_code IS 'Further definition of the type of crossing, one of {BRIDGE,CRTBOX,DAM,FORD,OVAL,PIPEARCH,ROUND,WEIR,WOODBOX,NULL}';
comment on column bcfishpass.crossings_vw.modelled_crossing_type_source IS 'List of sources that indicate if a modelled crossing is open bottom, Acceptable values are: FWA_EDGE_TYPE=double line river, FWA_STREAM_ORDER=stream order >=6, GBA_RAILWAY_STRUCTURE_LINES_SP=railway structure, "MANUAL FIX"=manually identified OBS, MOT_ROAD_STRUCTURE_SP=MoT structure, TRANSPORT_LINE_STRUCTURE_CODE=DRA structure}';
comment on column bcfishpass.crossings_vw.barrier_status IS 'The evaluation of the crossing as a barrier to the fish passage. From PSCIS, this is based on the FINAL SCORE value. For other data sources this varies. Acceptable Values are: PASSABLE - Passable, POTENTIAL - Potential or partial barrier, BARRIER - Barrier, UNKNOWN - Other';
comment on column bcfishpass.crossings_vw.pscis_road_name  IS 'PSCIS road name, taken from the PSCIS assessment data submission';
comment on column bcfishpass.crossings_vw.pscis_stream_name  IS 'PSCIS stream name, taken from the PSCIS assessment data submission';
comment on column bcfishpass.crossings_vw.pscis_assessment_comment  IS 'PSCIS assessment_comment, taken from the PSCIS assessment data submission';
comment on column bcfishpass.crossings_vw.pscis_assessment_date  IS 'PSCIS assessment_date, taken from the PSCIS assessment data submission';
comment on column bcfishpass.crossings_vw.pscis_final_score IS 'PSCIS final_score, taken from the PSCIS assessment data submission';
comment on column bcfishpass.crossings_vw.transport_line_structured_name_1 IS 'DRA road name, taken from the nearest DRA road (within 30m)';
comment on column bcfishpass.crossings_vw.transport_line_type_description IS 'DRA road type, taken from the nearest DRA road (within 30m)';
comment on column bcfishpass.crossings_vw.transport_line_surface_description IS 'DRA road surface, taken from the nearest DRA road (within 30m)';
comment on column bcfishpass.crossings_vw.ften_forest_file_id IS 'FTEN road forest_file_id value, taken from the nearest FTEN road (within 30m)';
comment on column bcfishpass.crossings_vw.ften_road_section_id IS 'FTEN road road_section_id value, taken from the nearest FTEN road (within 30m)';
comment on column bcfishpass.crossings_vw.ften_file_type_description IS 'FTEN road tenure type (Forest Service Road, Road Permit, etc), taken from the nearest FTEN road (within 30m)';
comment on column bcfishpass.crossings_vw.ften_client_number IS 'FTEN road client number, taken from the nearest FTEN road (within 30m)';
comment on column bcfishpass.crossings_vw.ften_client_name IS 'FTEN road client name, taken from the nearest FTEN road (within 30m)';
comment on column bcfishpass.crossings_vw.ften_life_cycle_status_code IS 'FTEN road life_cycle_status_code (active or retired, pending roads are not included), taken from the nearest FTEN road (within 30m)';
comment on column bcfishpass.crossings_vw.ften_map_label IS 'FTEN road map_label value, taken from the nearest FTEN road (within 30m)';
comment on column bcfishpass.crossings_vw.rail_track_name IS 'Railway name, taken from nearest railway (within 25m)';
comment on column bcfishpass.crossings_vw.rail_owner_name IS 'Railway owner name, taken from nearest railway (within 25m)';
comment on column bcfishpass.crossings_vw.rail_operator_english_name IS 'Railway operator name, taken from nearest railway (within 25m)';;
comment on column bcfishpass.crossings_vw.ogc_proponent IS 'OGC road tenure proponent (currently modelled crossings only, taken from OGC road that crosses the stream)';
comment on column bcfishpass.crossings_vw.dam_name IS 'See CABD dams column: dam_name_en';
comment on column bcfishpass.crossings_vw.dam_height IS 'See CABD dams column: dam_height';
comment on column bcfishpass.crossings_vw.dam_owner IS 'See CABD dams column: owner';
comment on column bcfishpass.crossings_vw.dam_use IS 'See CABD table dam_use_codes';
comment on column bcfishpass.crossings_vw.dam_operating_status IS 'See CABD dams column dam_operating_status';
comment on column bcfishpass.crossings_vw.utm_zone IS 'UTM ZONE is a segment of the Earths surface 6 degrees of longitude in width. The zones are numbered eastward starting at the meridian 180 degrees from the prime meridian at Greenwich. There are five zones numbered 7 through 11 that cover British Columbia, e.g., Zone 10 with a central meridian at -123 degrees.';
comment on column bcfishpass.crossings_vw.utm_easting IS 'UTM EASTING is the distance in meters eastward to or from the central meridian of a UTM zone with a false easting of 500000 meters. e.g., 440698';
comment on column bcfishpass.crossings_vw.utm_northing IS 'UTM NORTHING is the distance in meters northward from the equator. e.g., 6197826';
comment on column bcfishpass.crossings_vw.linear_feature_id IS 'From BC FWA, the unique identifier for a stream segment (flow network arc)';
comment on column bcfishpass.crossings_vw.blue_line_key IS 'From BC FWA, uniquely identifies a single flow line such that a main channel and a secondary channel with the same watershed code would have different blue line keys (the Fraser River and all side channels have different blue line keys).';
comment on column bcfishpass.crossings_vw.watershed_key IS 'From BC FWA, a key that identifies a stream system. There is a 1:1 match between a watershed key and watershed code. The watershed key will match the blue line key for the mainstem.';
comment on column bcfishpass.crossings_vw.downstream_route_measure IS 'The distance, in meters, along the blue_line_key from the mouth of the stream/blue_line_key to the feature.';
comment on column bcfishpass.crossings_vw.wscode IS 'A truncated version of the BC FWA fwa_watershed_code (trailing zeros removed and "-" replaced with ".", stored as postgres type ltree for fast tree based queries';
comment on column bcfishpass.crossings_vw.localcode IS 'A truncated version of the BC FWA local_watershed_code (trailing zeros removed and "-" replaced with ".", stored as postgres type ltree for fast tree based queries';;
comment on column bcfishpass.crossings_vw.watershed_group_code IS 'The watershed group code associated with the feature.';
comment on column bcfishpass.crossings_vw.gnis_stream_name IS 'The BCGNIS (BC Geographical Names Information System) name associated with the FWA stream';
comment on column bcfishpass.crossings_vw.stream_order IS 'Order of FWA stream at point';
comment on column bcfishpass.crossings_vw.stream_magnitude IS 'Magnitude of FWA stream at point';
comment on column bcfishpass.crossings_vw.upstream_area_ha IS 'Cumulative area upstream of the end of the stream (as defined by linear_feature_id)';
comment on column bcfishpass.crossings_vw.stream_order_parent IS 'Stream order of the stream into which the stream drains';
comment on column bcfishpass.crossings_vw.stream_order_max IS 'Maximum stream order associated with the stream (as defined by blue_line_key)';
comment on column bcfishpass.crossings_vw.map_upstream IS 'Mean annual precipitation for the watershed upstream of the stream segment (as defined by linear_feature_id)';
comment on column bcfishpass.crossings_vw.channel_width IS 'Modelled channel width of the stream (m)';
comment on column bcfishpass.crossings_vw.mad_m3s IS 'Modelled mean annual discharge of the stream (m3/s)';
comment on column bcfishpass.crossings_vw.observedspp_dnstr IS 'Species codes of downstream fish observations';
comment on column bcfishpass.crossings_vw.observedspp_upstr IS 'Species codes of upstream fish observations';
comment on column bcfishpass.crossings_vw.crossings_dnstr IS 'aggregated_crossings_id value for all downstream crossings';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_dnstr IS 'aggregated_crossings_id value for all downstream anthropogenic barriers';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_dnstr_count IS 'Count of anthropogenic downstream barriers';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_upstr IS 'aggregated_crossings_id value for all upstream anthropogenic barriers';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_upstr_count IS 'Count of all upstream anthropogenic barriers';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_bt_upstr IS 'aggregated_crossings_id value for upstream anthropogenic barriers on streams accessible to Bull Trout';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_upstr_bt_count IS 'Count of upstream anthropogenic barriers on streams accessible to Bull Trout';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_ch_cm_co_pk_sk_upstr IS 'aggregated_crossings_id value for upstream anthropogenic barriers on streams accessible to Pacific Salmon';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_ch_cm_co_pk_sk_upstr_count IS 'Count of upstream anthropogenic barriers on streams accessible to Pacific Salmon';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_st_upstr IS 'aggregated_crossings_id value for upstream anthropogenic barriers on streams accessible to Steelhead';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_st_upstr_count IS 'Count of upstream anthropogenic barriers on streams accessible to Steelhead';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_wct_upstr IS 'aggregated_crossings_id value for upstream anthropogenic barriers on streams accessible to West Slope Cutthroat Trout';
comment on column bcfishpass.crossings_vw.barriers_anthropogenic_wct_upstr_count IS 'Count of upstream anthropogenic barriers on streams accessible to Bull Trout';
comment on column bcfishpass.crossings_vw.gradient IS 'Gradient of stream segment at crossing (defined by stream_segment_id)';
comment on column bcfishpass.crossings_vw.total_network_km IS 'Total upstream length of FWA stream network (km)';
comment on column bcfishpass.crossings_vw.total_stream_km IS 'Total upstream length of FWA streams (single and double line, km)';
comment on column bcfishpass.crossings_vw.total_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs (ha)';
comment on column bcfishpass.crossings_vw.total_wetland_ha IS 'Total upstream area of wetlands (ha)';
comment on column bcfishpass.crossings_vw.total_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies (km)';
comment on column bcfishpass.crossings_vw.total_slopeclass03_km IS 'Total upstream length of stream < 3% gradient (km)';
comment on column bcfishpass.crossings_vw.total_slopeclass05_km IS 'Total upstream length of stream < 5% gradient (km)';
comment on column bcfishpass.crossings_vw.total_slopeclass08_km IS 'Total upstream length of stream < 8% gradient (km)';
comment on column bcfishpass.crossings_vw.total_slopeclass15_km IS 'Total upstream length of stream < 15% gradient (km)';
comment on column bcfishpass.crossings_vw.total_slopeclass22_km IS 'Total upstream length of stream < 22% gradient (km)';
comment on column bcfishpass.crossings_vw.total_slopeclass30_km IS 'Total upstream length of stream < 30% gradient (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_network_km IS 'Total upstream length of FWA stream network, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_stream_km IS 'Total upstream length of FWA streams, downstream of any anthropogenic barrier  (single and double line, km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_wetland_ha IS 'Total upstream area of wetlands, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_slopeclass03_km IS 'Total upstream length of stream < 3% gradient, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_slopeclass05_km IS 'Total upstream length of stream < 5% gradient, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_slopeclass08_km IS 'Total upstream length of stream < 8% gradient, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_slopeclass15_km IS 'Total upstream length of stream < 15% gradient, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_slopeclass22_km IS 'Total upstream length of stream < 22% gradient, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.total_belowupstrbarriers_slopeclass30_km IS 'Total upstream length of stream < 30% gradient, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.barriers_bt_dnstr IS 'aggregated_crossings_id value for downstream anthropogenic barriers on streams accessible to Bull Trout';
comment on column bcfishpass.crossings_vw.bt_network_km IS 'Total upstream length of FWA stream network accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_stream_km IS 'Total upstream length of FWA streams accessible to Bull Trout (single and double line, km)';
comment on column bcfishpass.crossings_vw.bt_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to Bull Trout (ha)';
comment on column bcfishpass.crossings_vw.bt_wetland_ha IS 'Total upstream area of wetlands accessible to Bull Trout (ha)';
comment on column bcfishpass.crossings_vw.bt_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to Bull Trout (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_network_km IS 'Total upstream length of FWA stream network accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_stream_km IS 'Total upstream length of FWA streams accessible to Bull Trout, downstream of any anthropogenic barrier  (single and double line, km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to Bull Trout, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_wetland_ha IS 'Total upstream area of wetlands accessible to Bull Trout, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_belowupstrbarriers_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to Bull Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.barriers_ch_cm_co_pk_sk_dnstr IS 'aggregated_crossings_id value for downstream anthropogenic barriers on streams accessible to Pacific Salmon';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_network_km IS 'Total upstream length of FWA stream network accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_stream_km IS 'Total upstream length of FWA streams accessible to Pacific Salmon (single and double line, km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to Pacific Salmon (ha)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_wetland_ha IS 'Total upstream area of wetlands accessible to Pacific Salmon (ha)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to Pacific Salmon (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_network_km IS 'Total upstream length of FWA stream network accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_stream_km IS 'Total upstream length of FWA streams accessible to Pacific Salmon, downstream of any anthropogenic barrier  (single and double line, km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to Pacific Salmon, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_wetland_ha IS 'Total upstream area of wetlands accessible to Pacific Salmon, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.ch_cm_co_pk_sk_belowupstrbarriers_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to Pacific Salmon, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.barriers_st_dnstr IS 'aggregated_crossings_id value for downstream anthropogenic barriers on streams accessible to Steelhead';
comment on column bcfishpass.crossings_vw.st_network_km IS 'Total upstream length of FWA stream network accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_stream_km IS 'Total upstream length of FWA streams accessible to Steelhead (single and double line, km)';
comment on column bcfishpass.crossings_vw.st_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to Steelhead (ha)';
comment on column bcfishpass.crossings_vw.st_wetland_ha IS 'Total upstream area of wetlands accessible to Steelhead (ha)';
comment on column bcfishpass.crossings_vw.st_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to Steelhead (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_network_km IS 'Total upstream length of FWA stream network accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_stream_km IS 'Total upstream length of FWA streams accessible to Steelhead, downstream of any anthropogenic barrier  (single and double line, km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to Steelhead, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_wetland_ha IS 'Total upstream area of wetlands accessible to Steelhead, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.st_belowupstrbarriers_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to Steelhead, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.barriers_wct_dnstr IS 'aggregated_crossings_id value for downstream anthropogenic barriers on streams accessible to West Slope Cutthroat Trout';
comment on column bcfishpass.crossings_vw.wct_network_km IS 'Total upstream length of FWA stream network accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_stream_km IS 'Total upstream length of FWA streams accessible to West Slope Cutthroat Trout (single and double line, km)';
comment on column bcfishpass.crossings_vw.wct_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to West Slope Cutthroat Trout (ha)';
comment on column bcfishpass.crossings_vw.wct_wetland_ha IS 'Total upstream area of wetlands accessible to West Slope Cutthroat Trout (ha)';
comment on column bcfishpass.crossings_vw.wct_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to West Slope Cutthroat Trout (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_network_km IS 'Total upstream length of FWA stream network accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_stream_km IS 'Total upstream length of FWA streams accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier  (single and double line, km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_lakereservoir_ha IS 'Total upstream area of lakes and reservoirs accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_wetland_ha IS 'Total upstream area of wetlands accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier  (ha)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_slopeclass03_waterbodies_km IS 'Total upstream length of stream < 3% gradient and connected waterbodies accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_slopeclass03_km IS 'Total upstream length of stream < 3% gradient accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_slopeclass05_km IS 'Total upstream length of stream < 5% gradient accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_slopeclass08_km IS 'Total upstream length of stream < 8% gradient accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_slopeclass15_km IS 'Total upstream length of stream < 15% gradient accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_slopeclass22_km IS 'Total upstream length of stream < 22% gradient accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.wct_belowupstrbarriers_slopeclass30_km IS 'Total upstream length of stream < 30% gradient accessible to West Slope Cutthroat Trout, downstream of any anthropogenic barrier (km)';
comment on column bcfishpass.crossings_vw.bt_spawning_km IS 'Upstream length of modelled/observed Bull Trout spawning';
comment on column bcfishpass.crossings_vw.bt_rearing_km IS 'Upstream length of modelled/observed Bull Trout Rearing';
comment on column bcfishpass.crossings_vw.bt_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed Bull Trout spawning, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.bt_rearing_belowupstrbarriers_km IS 'Upstream length of modelled/observed Bull Trout rearing, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.ch_spawning_km IS 'Upstream length of modelled/observed Chinook spawning';
comment on column bcfishpass.crossings_vw.ch_rearing_km IS 'Upstream length of modelled/observed Chinook Rearing';
comment on column bcfishpass.crossings_vw.ch_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed Chinook spawning, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.ch_rearing_belowupstrbarriers_km IS 'Upstream length of modelled/observed Chinook rearing, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.cm_spawning_km IS 'Upstream length of modelled/observed Chum spawning';
comment on column bcfishpass.crossings_vw.cm_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed Chum spawning, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.co_spawning_km IS 'Upstream length of modelled/observed Coho spawning';
comment on column bcfishpass.crossings_vw.co_rearing_km IS 'Upstream length of modelled/observed Coho rearing';
comment on column bcfishpass.crossings_vw.co_rearing_ha IS 'Upstream area (wetlands) of modelled/observed Coho rearing';
comment on column bcfishpass.crossings_vw.co_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed Coho spawning, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.co_rearing_belowupstrbarriers_km IS 'Upstream length of modelled/observed Coho rearing, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.co_rearing_belowupstrbarriers_ha IS 'Upstream area (wetlands) of modelled/observed Coho rearing, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.pk_spawning_km IS 'Upstream length of modelled/observed Pink spawning';
comment on column bcfishpass.crossings_vw.pk_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed Pink spawning, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.sk_spawning_km IS 'Upstream length of modelled/observed Sockeye spawning';
comment on column bcfishpass.crossings_vw.sk_rearing_km IS 'Upstream length of modelled/observed Sockeye rearing';
comment on column bcfishpass.crossings_vw.sk_rearing_ha IS 'Upstream area (lakes) of modelled/observed Sockeye rearing';
comment on column bcfishpass.crossings_vw.sk_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed Sockeye spawning';
comment on column bcfishpass.crossings_vw.sk_rearing_belowupstrbarriers_km IS 'Upstream length of modelled/observed Sockeye rearing';
comment on column bcfishpass.crossings_vw.sk_rearing_belowupstrbarriers_ha IS 'Upstream area (lakes) of modelled/observed Sockeye rearing';
comment on column bcfishpass.crossings_vw.st_spawning_km IS 'Upstream length of modelled/observed Steelhead spawning';
comment on column bcfishpass.crossings_vw.st_rearing_km IS 'Upstream length of modelled/observed Steelhead Rearing';
comment on column bcfishpass.crossings_vw.st_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed Steelhead spawning, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.st_rearing_belowupstrbarriers_km IS 'Upstream length of modelled/observed Steelhead rearing, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.wct_spawning_km IS 'Upstream length of modelled/observed West Slope Cutthroat Trout spawning';
comment on column bcfishpass.crossings_vw.wct_rearing_km IS 'Upstream length of modelled/observed West Slope Cutthroat Trout Rearing';
comment on column bcfishpass.crossings_vw.wct_spawning_belowupstrbarriers_km IS 'Upstream length of modelled/observed West Slope Cutthroat Trout spawning, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.wct_rearing_belowupstrbarriers_km IS 'Upstream length of modelled/observed West Slope Cutthroat Trout rearing, downstream of any anthropogenic barriers';
comment on column bcfishpass.crossings_vw.geom IS 'The point geometry associated with the feature';

-- streams_vw

comment on column bcfishpass.streams_vw.segmented_stream_id IS 'Unique id for the stream segment based on existing segmentation. Value is concatenation of blue_line_key.downstream_route_measure';
comment on column bcfishpass.streams_vw.linear_feature_id IS 'FWA stream segment unique identifier';
comment on column bcfishpass.streams_vw.edge_type IS 'From BC FWA, the unique identifier for a stream segment (flow network arc)';
comment on column bcfishpass.streams_vw.blue_line_key IS 'From BC FWA, uniquely identifies a single flow line such that a main channel and a secondary channel with the same watershed code would have different blue line keys (the Fraser River and all side channels have different blue line keys).';
comment on column bcfishpass.streams_vw.watershed_key IS 'From BC FWA, a key that identifies a stream system. There is a 1:1 match between a watershed key and watershed code. The watershed key will match the blue line key for the mainstem.';
comment on column bcfishpass.streams_vw.watershed_group_code IS 'The watershed group code associated with the feature.';
comment on column bcfishpass.streams_vw.downstream_route_measure IS 'The distance, in meters, along the blue_line_key from the mouth of the stream/blue_line_key to the feature.';
comment on column bcfishpass.streams_vw.length_metre IS 'The watershed group code associated with the feature.';
comment on column bcfishpass.streams_vw.waterbody_key IS 'The waterbody key of the waterbody the edge is contained within.';
comment on column bcfishpass.streams_vw.wscode IS 'A truncated version of the BC FWA fwa_watershed_code (trailing zeros removed and ''-'' replaced with ''.''';
comment on column bcfishpass.streams_vw.localcode IS 'A truncated version of the BC FWA local_watershed_code (trailing zeros removed and ''-'' replaced with ''.''';
comment on column bcfishpass.streams_vw.gnis_name IS 'The BCGNIS (BC Geographical Names Information System) name associated with the FWA stream';
comment on column bcfishpass.streams_vw.stream_order IS 'Order of FWA stream';
comment on column bcfishpass.streams_vw.stream_magnitude IS 'Magnitude of FWA stream';
comment on column bcfishpass.streams_vw.gradient IS 'Gradient of the stream segment';
comment on column bcfishpass.streams_vw.feature_code IS 'A value based on the Canadian Council of Surveys and Mapping''s (CCSM) system for classification of geographic features.';
comment on column bcfishpass.streams_vw.upstream_route_measure IS 'The distance, in meters, along the blue_line_key from the mouth of the stream/blue_line_key to the upstream end of the feature.';
comment on column bcfishpass.streams_vw.upstream_area_ha IS 'Cumulative area upstream of the end of the stream (as defined by linear_feature_id)';
comment on column bcfishpass.streams_vw.stream_order_parent IS 'Stream order of the stream into which the stream drains';
comment on column bcfishpass.streams_vw.stream_order_max IS 'Maximum stream order associated with the stream (as defined by blue_line_key)';
comment on column bcfishpass.streams_vw.map_upstream IS 'Mean annual precipitation for the watershed upstream of the stream segment (as defined by linear_feature_id)';
comment on column bcfishpass.streams_vw.channel_width IS 'Modelled channel width of the stream (m)';
comment on column bcfishpass.streams_vw.mad_m3s IS 'Modelled mean annual discharge of the stream (m3/s)';
comment on column bcfishpass.streams_vw.barriers_anthropogenic_dnstr IS 'aggregated_crossings_id value for all downstream anthropogenic barriers';
comment on column bcfishpass.streams_vw.barriers_pscis_dnstr IS 'aggregated_crossings_id value for all downstream PSCIS assessed barriers';
comment on column bcfishpass.streams_vw.barriers_dams_dnstr IS 'aggregated_crossings_id value for all downstream dams that are barriers';
comment on column bcfishpass.streams_vw.barriers_dams_hydro_dnstr IS 'aggregated_crossings_id value for all downstream hydroelectricity dam that are barriers';
comment on column bcfishpass.streams_vw.barriers_bt_dnstr IS 'aggregated_crossings_id value for downstream natural barriers to Bull Trout';
comment on column bcfishpass.streams_vw.barriers_ch_cm_co_pk_sk_dnstr IS 'aggregated_crossings_id value for downstream natural barriers to Pacific Salmon';
comment on column bcfishpass.streams_vw.barriers_ct_dv_rb_dnstr IS 'aggregated_crossings_id value for downstream natural barriers to Cutthroat Trout/Dolly Varden/Rainbow Trout';
comment on column bcfishpass.streams_vw.barriers_st_dnstr IS 'aggregated_crossings_id value for downstream natural barriers to Steelhead';
comment on column bcfishpass.streams_vw.barriers_wct_dnstr IS 'aggregated_crossings_id value for downstream natural barriers to West Slope Cutthroat Trout';
comment on column bcfishpass.streams_vw.crossings_dnstr IS 'aggregated_crossings_id value for all crossings downstream';
comment on column bcfishpass.streams_vw.dam_dnstr_ind IS 'Indicates if the next anthropogenic barrier downstream is a dam';
comment on column bcfishpass.streams_vw.dam_hydro_dnstr_ind IS 'Indicates if the next anthropogenic barrier downstream is a hydroelectric dam';
comment on column bcfishpass.streams_vw.remediated_dnstr_ind IS 'Indicates if the next crossing downstream is a remediated PSCIS site';
comment on column bcfishpass.streams_vw.obsrvtn_event_upstr IS 'id value for all upstream target species fish observations';
comment on column bcfishpass.streams_vw.obsrvtn_species_codes_upstr IS 'Unique species codes for all upstream target species observations (in watershed group)';
comment on column bcfishpass.streams_vw.access_bt IS 'Bull Trout accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_ch IS 'Chinook accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_cm IS 'Chum accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_co IS 'Coho accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_pk IS 'Pink accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_sk IS 'Sockeye accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_st IS 'Steelhead accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_wct IS 'West Slope Cutthroat Trout accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.access_salmon IS 'Pacific Salmon (all): accessibility model: -1=not modelled; 0=natural barrier downstream; 1=modelled accessible; 2=observed accessible';
comment on column bcfishpass.streams_vw.species_codes_dnstr IS 'Unique species codes for all downstream target species observations';
comment on column bcfishpass.streams_vw.spawning_bt IS 'Bull Trout spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.spawning_ch IS 'Chinook spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.spawning_cm IS 'Chum spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.spawning_co IS 'Coho spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.spawning_pk IS 'Pink spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.spawning_sk IS 'Sockeye spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.spawning_st IS 'Steelhead spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.spawning_wct IS 'West Slope Cutthroat Trout spawning model: -1=not modelled; 0=non spawning; 1=modelled spawning; 2=modelled and observed spawning; 3=observed spawning (not modelled)';
comment on column bcfishpass.streams_vw.rearing_bt IS 'Bull Trout rearing model: -1=not modelled; 0=non rearing; 1=modelled rearing; 2=modelled and observed rearing; 3=observed rearing (not modelled)';
comment on column bcfishpass.streams_vw.rearing_ch IS 'Chinook rearing model: -1=not modelled; 0=non rearing; 1=modelled rearing; 2=modelled and observed rearing; 3=observed rearing (not modelled)';
comment on column bcfishpass.streams_vw.rearing_co IS 'Coho rearing model: -1=not modelled; 0=non rearing; 1=modelled rearing; 2=modelled and observed rearing; 3=observed rearing (not modelled)';
comment on column bcfishpass.streams_vw.rearing_sk IS 'Sockeye rearing model: -1=not modelled; 0=non rearing; 1=modelled rearing; 2=modelled and observed rearing; 3=observed rearing (not modelled)';
comment on column bcfishpass.streams_vw.rearing_st IS 'Steelhead rearing model: -1=not modelled; 0=non rearing; 1=modelled rearing; 2=modelled and observed rearing; 3=observed rearing (not modelled)';
comment on column bcfishpass.streams_vw.rearing_wct IS 'West Slope Cutthroat rearing model: -1=not modelled; 0=non rearing; 1=modelled rearing; 2=modelled and observed rearing; 3=observed rearing (not modelled)';
comment on column bcfishpass.streams_vw.mapping_code_bt IS 'Stream mapping code for Bull Trout, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_ch IS 'Stream mapping code for Chinook, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_cm IS 'Stream mapping code for Chum, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_co IS 'Stream mapping code for Coho, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_pk IS 'Stream mapping code for Pink, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_sk IS 'Stream mapping code for Sockeye, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_st IS 'Stream mapping code for Steelhead, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_wct IS 'Stream mapping code for West Slope Cutthroat Trout, a string indicating: model output/downstream barrier status/stream type';
comment on column bcfishpass.streams_vw.mapping_code_salmon IS 'Stream mapping code for Pacific Salmon (all), a string indicating: model output/downstream barrier status/stream type';

COMMIT;