CREATE TABLE IF NOT EXISTS bcfishpass.streams 
(
  segmented_stream_id text primary key,
  linear_feature_id        bigint                      ,
  edge_type                integer                     ,
  blue_line_key            integer                     ,
  watershed_key            integer                     ,
  watershed_group_code     character varying(4)        ,
  downstream_route_measure double precision            ,
  length_metre             double precision            ,
  waterbody_key            integer                     ,
  wscode_ltree             ltree                       ,
  localcode_ltree          ltree                       ,
  gradient                 double precision            ,
  upstream_route_measure   double precision            ,
  barriers_majordams_dnstr integer[],
  barriers_subsurfaceflow_dnstr integer[],
  barriers_falls_dnstr integer[],
  barriers_gradient_05_dnstr integer[],
  barriers_gradient_07_dnstr integer[],
  barriers_gradient_10_dnstr integer[],
  barriers_gradient_15_dnstr integer[],
  barriers_gradient_20_dnstr integer[],
  barriers_gradient_25_dnstr integer[],
  barriers_gradient_30_dnstr integer[],
  barriers_other_definite_dnstr integer[],
  barriers_anthropogenic_dnstr integer[],
  barriers_pscis_dnstr integer[],
  barriers_remediated_dnstr integer[],
  obsrvtn_pnt_distinct_upstr integer[],
  accessibility_model_co_ch_sk text,
  accessibility_model_st text,
  accessibility_model_wct text,
  accessibility_model_pk text,
  accessibility_model_cm text,
  geom geometry(LineStringZM,3005)
);

CREATE INDEX IF NOT EXISTS streams_geom_idx ON bcfishpass.streams USING GIST (geom);