CREATE TABLE whse_basemapping.transport_line_divided_code (
        transport_line_divided_code character varying(1) PRIMARY KEY,
        description character varying(20) NOT NULL,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone
);

CREATE TABLE whse_basemapping.transport_line_structure_code (
        transport_line_structure_code character varying(1) PRIMARY KEY,
        description character varying(20) NOT NULL,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone
);

CREATE TABLE whse_basemapping.transport_line_surface_code (
        transport_line_surface_code character varying(1) PRIMARY KEY,
        description character varying(20) NOT NULL,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone
);

CREATE TABLE whse_basemapping.transport_line_type_code (
        transport_line_type_code character varying(3) PRIMARY KEY,
        description character varying(30) NOT NULL,
        demographic_ind character varying(1) NOT NULL,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone,
        road_class character varying(12) NOT NULL
);

CREATE TABLE whse_basemapping.transport_line (
        transport_line_id SERIAL PRIMARY KEY,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone,
        create_partner_org_id integer NOT NULL,
        create_partner_org character varying(110),
        modify_partner_org_id integer NOT NULL,
        modify_partner_org character varying(110),
        custodian_partner_org_id integer,
        custodian_partner_org character varying(110),
        data_capture_method_code character varying(30) NOT NULL,
        z_value_derived_ind character varying(1),
        capture_date timestamp with time zone,
        deactivation_date timestamp with time zone,
        transport_line_type_code character varying(3) NOT NULL,
        transport_line_surface_code character varying(1) NOT NULL,
        transport_line_divided_code character varying(1) NOT NULL,
        travel_direction_code character varying(1) NOT NULL,
        transport_line_structure_code character varying(1),
        speed_limit smallint NOT NULL,
        left_number_of_lanes smallint NOT NULL,
        right_number_of_lanes smallint NOT NULL,
        total_number_of_lanes smallint NOT NULL,
        under_construction_ind character varying(1) NOT NULL,
        virtual_ind character varying(1) NOT NULL,
        disaster_route_ind character varying(1) NOT NULL,
        truck_route_ind character varying(1) NOT NULL,
        left_locality_id integer,
        left_locality character varying(50),
        right_locality_id integer,
        right_locality character varying(50),
        left_regional_district_id character varying(5),
        right_regional_district_id character varying(5),
        structured_name_1_id integer,
        structured_name_1 character varying(100),
        structured_name_2_id integer,
        structured_name_2 character varying(100),
        structured_name_3_id integer,
        structured_name_3 character varying(100),
        structured_name_4_id integer,
        structured_name_4 character varying(100),
        structured_name_5_id integer,
        structured_name_5 character varying(100),
        structured_name_6_id integer,
        structured_name_6 character varying(100),
        structured_name_7_id integer,
        structured_name_7 character varying(100),
        highway_route_1 character varying(5),
        highway_route_2 character varying(5),
        highway_route_3 character varying(5),
        highway_exit_number character varying(5),
        industry_name_1 character varying(255),
        industry_name_2 character varying(255),
        industry_name_3 character varying(255),
        single_house_number integer,
        left_house_num_scheme_code character varying(1) NOT NULL,
        from_left_house_number integer,
        to_left_house_number integer,
        right_house_num_scheme_code character varying(1) NOT NULL,
        from_right_house_number integer,
        to_right_house_number integer,
        lane_restriction_code character varying(1),
        access_restriction_code character varying(2) NOT NULL,
        from_traffic_impactor_code character varying(1),
        to_traffic_impactor_code character varying(1),
        from_left_turn_time_code character varying(8),
        from_centre_turn_time_code character varying(8),
        from_right_turn_time_code character varying(8),
        to_left_turn_time_code character varying(8),
        to_centre_turn_time_code character varying(8),
        to_right_turn_time_code character varying(8),
        from_vehicle_max_weight_kg integer,
        to_vehicle_max_weight_kg integer,
        from_vehicle_max_width_metre double precision,
        to_vehicle_max_width_metre double precision,
        from_vehicle_max_height_metre double precision,
        to_vehicle_max_height_metre double precision,
        ministry_of_transport_id integer,
        ministry_of_transport_name character varying(255),
        integration_notes character varying(4000),
        excluded_rules character varying(4000),
        demographic_ind character varying(1) NOT NULL,
        extended_data character varying,
        ministry_of_transport_data character varying,
        from_navigation_rules character varying,
        along_navigation_rules character varying,
        to_navigation_rules character varying,
        from_transport_node_point_id integer,
        to_transport_node_point_id integer,
        geom geometry(MultiLineStringZ,3005)
);
CREATE INDEX transport_line_geom_geom_idx ON whse_basemapping.transport_line USING GIST (geom);