-- small scale streams - aggregate over blueline, class, order > 1
DROP TABLE IF EXISTS bcfishpass.carto_streams_large;

CREATE TABLE bcfishpass.carto_streams_large
(
  carto_stream_large_id serial primary key,
  blue_line_key             integer                           ,
  gnis_name                 character varying(80)            ,
  stream_order              integer                           ,
  access_model_bt    text,
  access_model_ch_co_sk    text,
  access_model_ch_co_sk_b    text,
  access_model_pk    text,
  access_model_st text,
  access_model_wct       text,
  spawning_model_ch    boolean,
  spawning_model_co    boolean,
  spawning_model_sk    boolean,
  spawning_model_st    boolean,
  spawning_model_wct   boolean,
  rearing_model_ch     boolean,
  rearing_model_co     boolean,
  rearing_model_sk     boolean,
  rearing_model_st     boolean,
  rearing_model_wct    boolean,
  geom geometry(LineString,3005)
);

INSERT INTO bcfishpass.carto_streams_large
  (blue_line_key,
  gnis_name,
  stream_order,
  access_model_bt,
  access_model_ch_co_sk,
  access_model_ch_co_sk_b,
  access_model_pk,
  access_model_st,
  access_model_wct,
  spawning_model_ch,
  spawning_model_co,
  spawning_model_sk,
  spawning_model_st,
  spawning_model_wct,
  rearing_model_ch,
  rearing_model_co,
  rearing_model_sk,
  rearing_model_st,
  rearing_model_wct,
  geom)
SELECT
  blue_line_key,
  gnis_name,
  stream_order,
  access_model_bt,
  access_model_ch_co_sk,
  access_model_ch_co_sk_b,
  access_model_pk,
  access_model_st,
  access_model_wct,
  spawning_model_ch,
  spawning_model_co,
  spawning_model_sk,
  spawning_model_st,
  spawning_model_wct,
  rearing_model_ch,
  rearing_model_co,
  rearing_model_sk,
  rearing_model_st,
  rearing_model_wct,
  (ST_Dump(ST_UNION(ST_Force2D(geom)))).geom as geom
FROM bcfishpass.streams
WHERE stream_order > 2
GROUP BY blue_line_key,
  gnis_name,
  stream_order,
  access_model_bt,
  access_model_ch_co_sk,
  access_model_ch_co_sk_b,
  access_model_pk,
  access_model_st,
  access_model_wct,
  spawning_model_ch,
  spawning_model_co,
  spawning_model_sk,
  spawning_model_st,
  spawning_model_wct,
  rearing_model_ch,
  rearing_model_co,
  rearing_model_sk,
  rearing_model_st,
  rearing_model_wct;