drop view if exists bcfishpass.streams_vw;
create or replace view bcfishpass.streams_vw as
select
  segmented_stream_id,
  linear_feature_id,
  edge_type,
  blue_line_key,
  watershed_key,
  watershed_group_code,
  downstream_route_measure,
  length_metre,
  waterbody_key,
  wscode_ltree,
  localcode_ltree,
  gnis_name,
  stream_order,
  stream_magnitude,
  gradient,
  feature_code,
  upstream_route_measure,
  upstream_area_ha,
  stream_order_parent,
  stream_order_max,
  map_upstream,
  channel_width,
  mad_m3s,
  array_to_string(barriers_anthropogenic_dnstr, ';') as barriers_anthropogenic_dnstr,
  array_to_string(barriers_pscis_dnstr, ';') as barriers_pscis_dnstr,
  array_to_string(barriers_bt_dnstr, ';') as barriers_bt_dnstr,
  array_to_string(barriers_ch_cm_co_pk_sk_dnstr, ';') as barriers_ch_cm_co_pk_sk_dnstr,
  array_to_string(barriers_ct_dv_rb_dnstr, ';') as barriers_ct_dv_rb_dnstr,
  array_to_string(barriers_st_dnstr, ';') as barriers_st_dnstr,
  array_to_string(barriers_wct_dnstr, ';') as barriers_wct_dnstr,
  array_to_string(crossings_dnstr, ';') as crossings_dnstr,
  dam_dnstr,
  dam_hydro_dnstr,
  remediated_dnstr,
  array_to_string(obsrvtn_event_upstr, ';') as obsrvtn_event_upstr,
  array_to_string(obsrvtn_species_codes_upstr, ';') as obsrvtn_species_codes_upstr,
  array_to_string(species_codes_dnstr, ';') as species_codes_dnstr,
  model_spawning_bt,
  model_spawning_ch,
  model_spawning_cm,
  model_spawning_co,
  model_spawning_pk,
  model_spawning_sk,
  model_spawning_st,
  model_spawning_wct,
  model_rearing_bt,
  model_rearing_ch,
  model_rearing_co,
  model_rearing_sk,
  model_rearing_st,
  model_rearing_wct,
  mapping_code_bt,
  mapping_code_ch,
  mapping_code_cm,
  mapping_code_co,
  mapping_code_pk,
  mapping_code_sk,
  mapping_code_st,
  mapping_code_wct,
  mapping_code_salmon,
  geom
from bcfishpass.streams;
