name: ng-prod-dump-schema
on:
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ENDPOINT_URL: https://nrs.objectstore.gov.bc.ca
  AWS_S3_ENDPOINT: nrs.objectstore.gov.bc.ca
  AWS_VIRTUAL_HOSTING: FALSE
  AWS_EC2_METADATA_DISABLED: True
  CPL_VSISTDIN_BUFFER_LIMIT: -1
concurrency:
  group: ng-prod
jobs:
  dump-schema:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Configure git safe directory
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            fetch-tags: true
            fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags --force
      - name: Dump schema
        run: |
          jobs/connect
          echo $(git describe)
          pg_dump $DATABASE_URL \
              --schema-only \
              --no-privileges \
              --no-owner \
              --table=whse_admin_boundaries.clab_indian_reserves \
              --table=whse_admin_boundaries.adm_indian_reserves_bands_sp \
              --table=whse_legal_admin_boundaries.abms_regional_districts_sp \
              --table=whse_basemapping.dbm_mof_50k_grid \
              --table=whse_basemapping.gba_railway_tracks_sp \
              --table=whse_legal_admin_boundaries.abms_municipalities_sp \
              --table=whse_admin_boundaries.adm_nr_districts_spg \
              --table=whse_admin_boundaries.clab_national_parks \
              --table=whse_cadastre.pmbc_parcel_fabric_poly_svw \
              --table=whse_tantalis.ta_park_ecores_pa_svw > bcfishpass.sql
          pg_dump $DATABASE_URL \
              --schema-only \
              --no-privileges \
              --no-owner \
              --schema=bcfishpass >> bcfishpass.sql
