name: ng-debug
run-name: ${{ github.actor }} Run bcfishpass on test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'data/**'
concurrency:
  group: ng-test
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  debug_load_streams_upstr_observations:
    runs-on: ubuntu-latest
    environment: ng-test
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run:  |
          PSQL="psql $DATABASE_URL ON_ERROR_STOP=1"
          cd model/01_access
          $PSQL -c "truncate bcfishpass.streams_upstr_observations"
          $PSQL -f sql/load_streams_upstr_observations.sql -v wsg=HARR

