name: production-load-monthly
run-name: ${{ github.actor }} Monthly data refresh
on:
  schedule:
    - cron: '0 15 15 * *'
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  data-refresh:
    runs-on: ubuntu-latest
    environment: production
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run: |
          jobs/replicate_dra
          jobs/load_monthly