name: test-data
run-name: ${{ github.actor }} Load data files to test databases
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'data/*.csv'
env:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
jobs:
  test-data:
    runs-on: ubuntu-latest
    container: ghcr.io/smnorris/bcfishpass:main
    services:
      postgres:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out fwapg
        uses: actions/checkout@v4
        with: 
          repository: smnorris/fwapg
          path: fwapg
      - name: Create fwapg schema
        run:  |
          cd db && ./create.sh
        working-directory: fwapg
      - name: Check out bcfishpass
        uses: actions/checkout@v4  
      - name: Create bcfishpass schema
        run:  |
          cd db/sources
          psql $DATABASE_URL -v ON_ERROR_STOP=1 -f sql/schemas.sql
          psql $DATABASE_URL -v ON_ERROR_STOP=1 -f sql/bcfishobs.sql
          psql $DATABASE_URL -v ON_ERROR_STOP=1 -f sql/cabd.sql
          psql $DATABASE_URL -v ON_ERROR_STOP=1 -f sql/whse_basemapping.transport_line.sql
          bcdata bc2pg -e -c 1 whse_admin_boundaries.clab_indian_reserves
          bcdata bc2pg -e -c 1 whse_admin_boundaries.adm_indian_reserves_bands_sp
          bcdata bc2pg -e -c 1 whse_legal_admin_boundaries.abms_regional_districts_sp
          bcdata bc2pg -e -c 1 whse_basemapping.dbm_mof_50k_grid
          bcdata bc2pg -e -c 1 whse_basemapping.gba_railway_tracks_sp
          bcdata bc2pg -e -c 1 whse_legal_admin_boundaries.abms_municipalities_sp
          bcdata bc2pg -e -c 1 whse_admin_boundaries.adm_nr_districts_spg
          bcdata bc2pg -e -c 1 whse_admin_boundaries.clab_national_parks
          bcdata bc2pg -e -c 1 whse_cadastre.pmbc_parcel_fabric_poly_svw
          bcdata bc2pg -e -c 1 whse_tantalis.ta_park_ecores_pa_svw
          curl https://nrs.objectstore.gov.bc.ca/bchamp/bcfishpass.sql | psql -v ON_ERROR_STOP=1 $DATABASE_URL
          psql $DATABASE_URL -v ON_ERROR_STOP=1 -c \
          "\copy whse_fish.species_cd FROM PROGRAM 'curl -s https://raw.githubusercontent.com/smnorris/fishbc/master/data-raw/whse_fish_species_cd/whse_fish_species_cd.csv' delimiter ',' csv header"
      - name: Test data
        run:  |
          cp parameters/example_cwf/*csv parameters/
          jobs/load_csv